// State Laws & Schemes Data - Delhi, Uttar Pradesh, Karnataka
// Each state has exactly 20 cards across categories

import { LawScheme } from './lawsData';

// ================== DELHI (20 cards) ==================
export const DELHI_LAWS: LawScheme[] = [
  // Housing / Property
  {
    id: 'dl-rera',
    title: 'Delhi RERA',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'housing-property',
    tags: ['RERA', 'real estate', 'builder', 'homebuyer'],
    preview: 'Delhi Real Estate Regulatory Authority for project registration, complaints, and homebuyer protection.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Delhi RERA regulates real estate projects in NCT Delhi.', 'All projects must be registered before sale.', 'Online complaint filing for delays and defects.', 'Covers DDA, private builders, and cooperative societies.'] },
      { title: 'Why This Matters', content: ['Verify project registration', 'Check builder compliance history', 'File complaints online', 'Get refund for delayed projects', 'Quality assurance', 'Transparent pricing'] },
      { title: 'Common Real-Life Problems', content: ['Builder delayed possession', 'DDA flat issues', 'Quality defects', 'Hidden charges', 'Project not registered', 'Amenities missing'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit rera.delhi.gov.in', 'Step 2: Search project registration', 'Step 3: Verify builder details', 'Step 4: Register for complaint', 'Step 5: File complaint online', 'Step 6: Track status', 'Step 7: Attend hearings', 'Step 8: Get order executed', 'Step 9: Appeal if needed', 'Step 10: Follow up'] },
      { title: 'Documents Usually Required', content: ['Agreement for sale', 'Payment receipts', 'Builder correspondence', 'Brochure/advertisements', 'ID proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['Delhi RERA Portal: rera.delhi.gov.in', 'Delhi RERA Office', 'Helpline available on portal'] },
    ],
    officialLinks: [{ label: 'Delhi RERA', url: 'https://rera.delhi.gov.in' }],
  },
  {
    id: 'dl-rent-disputes',
    title: 'Delhi Rent Control & Disputes',
    type: 'law',
    level: 'state',
    stateCode: 'DL',
    category: 'housing-property',
    tags: ['rent', 'tenant', 'landlord', 'eviction'],
    preview: 'Delhi Rent Control Act provisions for fair rent, eviction grounds, and tenant-landlord dispute resolution.',
    tagLabel: 'Law',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Delhi Rent Control Act governs older tenancies.', 'New tenancies under Model Tenancy Act framework.', 'Rent Controller handles disputes.', 'Protection against arbitrary eviction.'] },
      { title: 'Why This Matters', content: ['Rent increase limits', 'Eviction only on specified grounds', 'Security deposit caps', 'Essential services protection', 'Quick dispute resolution', 'Succession rights'] },
      { title: 'Common Real-Life Problems', content: ['Illegal eviction attempts', 'Excessive rent demands', 'Deposit not returned', 'Maintenance disputes', 'Subletting issues', 'Unauthorized construction'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check applicable law', 'Step 2: Keep rent receipts', 'Step 3: Have written agreement', 'Step 4: For disputes, approach Rent Controller', 'Step 5: File petition with documents', 'Step 6: Attend hearings', 'Step 7: Get order', 'Step 8: Execute through court', 'Step 9: Appeal to Rent Control Tribunal', 'Step 10: Seek legal aid if needed'] },
      { title: 'Documents Usually Required', content: ['Rent agreement', 'Rent receipts', 'Utility bills', 'Communication records', 'ID proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['Rent Controller office', 'District Court', 'Rent Control Tribunal', 'Delhi Legal Services Authority'] },
    ],
    officialLinks: [{ label: 'Delhi Courts', url: 'https://delhicourts.nic.in' }],
  },
  {
    id: 'dl-property-mutation',
    title: 'Property Mutation & Land Records',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'housing-property',
    tags: ['property', 'mutation', 'land records', 'registration'],
    preview: 'Online services for property mutation, land records verification, and registration in Delhi.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Property mutation after purchase/inheritance essential.', 'Land records available online.', 'e-District for property services.', 'MCD for municipal records.'] },
      { title: 'Why This Matters', content: ['Property tax name change', 'Ownership proof', 'Required for sale', 'Loan purposes', 'Inheritance claims', 'Dispute prevention'] },
      { title: 'Common Real-Life Problems', content: ['Mutation application pending', 'Wrong ownership records', 'Inheritance mutation delayed', 'Property tax issues', 'Encumbrance certificate needed', 'Document verification failed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit e-District Delhi', 'Step 2: Apply for mutation', 'Step 3: Submit sale deed/death certificate', 'Step 4: Pay fees', 'Step 5: Verification process', 'Step 6: Track status online', 'Step 7: For MCD, visit MCD portal', 'Step 8: Update property tax records', 'Step 9: Get updated records', 'Step 10: Preserve documents'] },
      { title: 'Documents Usually Required', content: ['Sale deed', 'Previous ownership records', 'Death certificate (inheritance)', 'Property tax receipts', 'ID proof', 'Indemnity bond'] },
      { title: 'Where to Apply / Complain / Track', content: ['e-District Delhi: edistrict.delhigovt.nic.in', 'MCD Portal: mcdonline.nic.in', 'Sub-Registrar office', 'Tehsildar'] },
    ],
    officialLinks: [{ label: 'e-District Delhi', url: 'https://edistrict.delhigovt.nic.in' }, { label: 'MCD Online', url: 'https://mcdonline.nic.in' }],
  },

  // Legal / Grievance
  {
    id: 'dl-edistrict',
    title: 'e-District Delhi - Online Services',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'grievance',
    tags: ['certificate', 'services', 'government', 'online'],
    preview: 'Single portal for all Delhi government certificates and services including caste, income, domicile certificates.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['e-District provides 100+ government services online.', 'Certificates, licenses, and permits.', 'Status tracking and grievance redressal.', 'Integration with DigiLocker for digital certificates.'] },
      { title: 'Why This Matters', content: ['Apply from home', 'No middlemen', 'Track application status', 'Time-bound delivery', 'Digital certificates', 'Reduced corruption'] },
      { title: 'Common Real-Life Problems', content: ['Certificate application pending', 'Document verification failed', 'Wrong information in certificate', 'Deadline missed', 'Unable to track status', 'Office not responding'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit edistrict.delhigovt.nic.in', 'Step 2: Register with Aadhaar', 'Step 3: Select service', 'Step 4: Fill application', 'Step 5: Upload documents', 'Step 6: Pay fee if applicable', 'Step 7: Track status', 'Step 8: Download certificate', 'Step 9: For issues, use grievance section', 'Step 10: Escalate if needed'] },
      { title: 'Documents Usually Required', content: ['Aadhaar card', 'Address proof', 'Service-specific documents', 'Passport photos', 'Previous certificates'] },
      { title: 'Where to Apply / Complain / Track', content: ['e-District Portal', 'SDM office', 'Tehsil office', 'Helpline: 1076'] },
    ],
    officialLinks: [{ label: 'e-District Delhi', url: 'https://edistrict.delhigovt.nic.in' }],
  },
  {
    id: 'dl-efir',
    title: 'Delhi Police e-FIR & Complaints',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'grievance',
    tags: ['police', 'FIR', 'complaint', 'crime'],
    preview: 'Online FIR filing and complaint registration with Delhi Police for various offenses.',
    tagLabel: 'Portal',
    tagColor: '#EF4444',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Delhi Police offers online complaint registration.', 'e-FIR for certain categories of crimes.', 'Status tracking of complaints.', 'Emergency services through Dial 112.'] },
      { title: 'Why This Matters', content: ['Quick complaint registration', 'No need to visit station for minor issues', 'Track investigation status', 'Documentation for insurance', 'Transparent process', 'Accessible 24/7'] },
      { title: 'Common Real-Life Problems', content: ['Mobile theft', 'Vehicle theft', 'Lost documents', 'Online fraud', 'Harassment', 'Neighborhood disputes', 'Cheating cases'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit delhipolice.gov.in', 'Step 2: Select complaint type', 'Step 3: Fill details', 'Step 4: Upload evidence', 'Step 5: Get acknowledgment', 'Step 6: Track status', 'Step 7: Visit station if called', 'Step 8: For emergencies, dial 112', 'Step 9: Escalate to DCP if needed', 'Step 10: Use RTI for FIR copy'] },
      { title: 'Documents Usually Required', content: ['ID proof', 'Evidence documents', 'IMEI for mobile theft', 'RC for vehicle theft', 'Screenshots for cyber crime'] },
      { title: 'Where to Apply / Complain / Track', content: ['Delhi Police Portal: delhipolice.gov.in', 'Dial 112 for emergency', 'Nearest Police Station', 'Cyber Crime Portal'] },
    ],
    officialLinks: [{ label: 'Delhi Police', url: 'https://delhipolice.gov.in' }],
  },
  {
    id: 'dl-dlsa',
    title: 'Delhi Legal Services Authority (DLSA)',
    type: 'scheme',
    level: 'state',
    stateCode: 'DL',
    category: 'grievance',
    tags: ['legal aid', 'free lawyer', 'Lok Adalat'],
    preview: 'Free legal aid, Lok Adalat services, and legal awareness programs for Delhi residents.',
    tagLabel: 'Scheme',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['DLSA provides free legal services to eligible persons.', 'Lok Adalats for quick dispute settlement.', 'Legal aid clinics across Delhi.', 'Para-legal volunteer support in communities.'] },
      { title: 'Why This Matters', content: ['Free lawyer for court cases', 'Quick settlement in Lok Adalat', 'Legal awareness', 'Help for marginalized', 'Access to justice', 'Reduced litigation costs'] },
      { title: 'Common Real-Life Problems', content: ['Cannot afford lawyer', 'Need legal advice', 'Simple dispute settlement', 'Accident compensation', 'Family matters', 'Labour disputes', 'Consumer complaints'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit DLSA office at district court', 'Step 2: Check eligibility', 'Step 3: Fill application', 'Step 4: Submit documents', 'Step 5: Get panel lawyer', 'Step 6: For settlement, apply Lok Adalat', 'Step 7: Attend proceedings', 'Step 8: Use legal aid clinic', 'Step 9: Helpline: 1516', 'Step 10: Tele-law services available'] },
      { title: 'Documents Usually Required', content: ['Application form', 'Income proof', 'ID proof', 'Case documents', 'Eligibility certificate'] },
      { title: 'Where to Apply / Complain / Track', content: ['DLSA at district courts', 'Helpline: 1516', 'Tele-Law: 1800-180-7676', 'Legal aid clinics'] },
    ],
    officialLinks: [{ label: 'DLSA Delhi', url: 'https://dslsa.org' }],
  },

  // Women / Social
  {
    id: 'dl-women-commission',
    title: 'Delhi Commission for Women (DCW)',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'women-family',
    tags: ['women', 'harassment', 'complaint', 'protection'],
    preview: 'State body for women\'s safety, complaint redressal, and protection against violence and harassment.',
    tagLabel: 'Portal',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['DCW handles women\'s complaints and protection.', 'Can summon police and officials.', 'Conducts inspections and inquiries.', 'Works with One Stop Centres.'] },
      { title: 'Why This Matters', content: ['Quick response to women\'s issues', 'Police action coordination', 'Counseling support', 'Policy advocacy', 'Legal support linkage', 'Helpline 181'] },
      { title: 'Common Real-Life Problems', content: ['Domestic violence', 'Workplace harassment', 'Stalking', 'Police inaction', 'Dowry harassment', 'Property disputes', 'Maintenance issues'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Call 181 Women Helpline', 'Step 2: Visit DCW office', 'Step 3: File complaint online/offline', 'Step 4: Provide evidence', 'Step 5: DCW issues notice', 'Step 6: Hearing conducted', 'Step 7: Counseling offered', 'Step 8: Police action directed', 'Step 9: Follow up on action', 'Step 10: Legal aid linkage'] },
      { title: 'Documents Usually Required', content: ['Complaint letter', 'ID proof', 'Evidence', 'FIR copy if filed', 'Medical reports'] },
      { title: 'Where to Apply / Complain / Track', content: ['Women Helpline: 181', 'DCW Office: Vikas Bhawan', 'Online complaint portal', 'One Stop Centres'] },
    ],
    officialLinks: [{ label: 'DCW Delhi', url: 'https://dcw.delhigovt.nic.in' }],
  },
  {
    id: 'dl-labour-portal',
    title: 'Delhi Labour Welfare & Wage Portal',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'employment',
    tags: ['labour', 'wages', 'worker', 'complaint'],
    preview: 'Portal for labour complaints, minimum wages information, and worker welfare schemes in Delhi.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Labour Department handles worker complaints.', 'Minimum wage notifications.', 'Building workers welfare board.', 'Shop establishment registration.'] },
      { title: 'Why This Matters', content: ['Minimum wage enforcement', 'Worker complaint redressal', 'Welfare scheme access', 'Legal protection', 'Safe working conditions', 'Benefits registration'] },
      { title: 'Common Real-Life Problems', content: ['Below minimum wage payment', 'Salary not paid', 'Wrongful termination', 'No provident fund', 'Unsafe conditions', 'No leave sanctioned'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check minimum wage notification', 'Step 2: Document wage records', 'Step 3: File complaint at Labour office', 'Step 4: Or use online portal', 'Step 5: Attend conciliation meeting', 'Step 6: Labour Court if unresolved', 'Step 7: Building workers register for welfare', 'Step 8: Claim benefits', 'Step 9: Join trade union', 'Step 10: Seek legal aid'] },
      { title: 'Documents Usually Required', content: ['Employment proof', 'Salary slips', 'Bank statements', 'Communication records', 'ID proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['Labour Department: labour.delhi.gov.in', 'Labour Commissioner office', 'Labour Court', 'Building Workers Board'] },
    ],
    officialLinks: [{ label: 'Labour Delhi', url: 'https://labour.delhi.gov.in' }],
  },

  // Health / Welfare
  {
    id: 'dl-mohalla-clinics',
    title: 'Mohalla Clinics - Free Healthcare',
    type: 'scheme',
    level: 'state',
    stateCode: 'DL',
    category: 'health-pension',
    tags: ['health', 'clinic', 'free treatment', 'medicine'],
    preview: 'Free primary healthcare through neighborhood clinics with free medicines and tests.',
    tagLabel: 'Scheme',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Mohalla Clinics provide free primary healthcare.', '200+ clinics across Delhi.', 'Free consultation, medicines, and basic tests.', 'Walk-in facility, no appointment needed.'] },
      { title: 'Why This Matters', content: ['Free treatment at doorstep', 'No long hospital queues', 'Basic tests free', 'Essential medicines free', 'Referral to hospitals', 'Morning and evening timings'] },
      { title: 'Common Real-Life Problems', content: ['Clinic closed', 'Medicines not available', 'Doctor not present', 'Long waiting time', 'Tests not done', 'Referral issues'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Find nearest Mohalla Clinic', 'Step 2: Visit during working hours', 'Step 3: Get token', 'Step 4: Free consultation', 'Step 5: Free tests done', 'Step 6: Free medicines given', 'Step 7: Follow-up visit if needed', 'Step 8: Referral to hospital for serious cases', 'Step 9: Feedback to improve services', 'Step 10: Report issues to health dept'] },
      { title: 'Documents Usually Required', content: ['Aadhaar card (preferred)', 'Any ID proof', 'Previous prescriptions (if follow-up)'] },
      { title: 'Where to Apply / Complain / Track', content: ['Nearest Mohalla Clinic', 'Health Department Delhi', 'CM Helpline', 'PWD (for infrastructure)'] },
    ],
    officialLinks: [{ label: 'Health Delhi', url: 'https://health.delhigovt.nic.in' }],
  },
  {
    id: 'dl-free-electricity',
    title: 'Free Electricity Scheme (200 Units)',
    type: 'scheme',
    level: 'state',
    stateCode: 'DL',
    category: 'utilities',
    tags: ['electricity', 'subsidy', 'free', 'utility'],
    preview: 'Free electricity for consumers using up to 200 units per month and 50% subsidy up to 400 units.',
    tagLabel: 'Scheme',
    tagColor: '#22C55E',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Zero bill for consumption up to 200 units.', '50% subsidy for 201-400 units.', 'Direct benefit to domestic consumers.', 'Automatic application through billing.'] },
      { title: 'Why This Matters', content: ['Significant saving on electricity', 'No application needed', 'Automatic benefit', 'Helps low-income families', 'Encourages conservation', 'Transparent billing'] },
      { title: 'Common Real-Life Problems', content: ['Subsidy not applied', 'Bill still showing charges', 'Meter reading disputes', 'Connection type wrong', 'Arrears added', 'High bill suddenly'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check meter reading', 'Step 2: Verify connection type is domestic', 'Step 3: Subsidy automatic if eligible', 'Step 4: Check bill details', 'Step 5: For issues, contact BSES/TATA Power', 'Step 6: Use grievance portal', 'Step 7: Visit customer care', 'Step 8: Approach electricity ombudsman', 'Step 9: Keep meter reading records', 'Step 10: Report theft/tampering'] },
      { title: 'Documents Usually Required', content: ['Electricity bill', 'Consumer number', 'ID proof for disputes'] },
      { title: 'Where to Apply / Complain / Track', content: ['BSES Portal/App', 'TATA Power Portal', 'Discom customer care', 'Electricity Ombudsman'] },
    ],
    officialLinks: [{ label: 'BSES', url: 'https://www.bsesdelhi.com' }],
  },
  {
    id: 'dl-free-bus-women',
    title: 'Free Bus Travel for Women',
    type: 'scheme',
    level: 'state',
    stateCode: 'DL',
    category: 'women-family',
    tags: ['bus', 'transport', 'women', 'free travel'],
    preview: 'Free travel for women in DTC and cluster buses across Delhi NCT.',
    tagLabel: 'Scheme',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Women can travel free in DTC buses.', 'Also applicable to cluster/orange buses.', 'Pink ticket issued to women.', 'No pass or registration required.'] },
      { title: 'Why This Matters', content: ['Financial relief for women', 'Encourages public transport', 'Improves mobility', 'Safety in public transport', 'No documentation needed', 'Available across Delhi'] },
      { title: 'Common Real-Life Problems', content: ['Conductor not giving pink ticket', 'Harassment in buses', 'Bus not stopping', 'Route confusion', 'Overcrowding', 'Misbehavior reported'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Board DTC or cluster bus', 'Step 2: Ask conductor for pink ticket', 'Step 3: No payment required', 'Step 4: Keep ticket till journey end', 'Step 5: For complaints, note bus number', 'Step 6: Complain to DTC helpline', 'Step 7: Use women helpline for harassment', 'Step 8: Tweet to DTC for response', 'Step 9: File RTI for records', 'Step 10: Give feedback for improvement'] },
      { title: 'Documents Usually Required', content: ['No documents required', 'Just be a woman passenger'] },
      { title: 'Where to Apply / Complain / Track', content: ['DTC Helpline', 'Women Helpline: 181', 'DTC Twitter handle', 'Transport Department'] },
    ],
    officialLinks: [{ label: 'DTC Delhi', url: 'https://dtc.delhi.gov.in' }],
  },

  // Education / Scholarships
  {
    id: 'dl-scholarships',
    title: 'Delhi Student Scholarships',
    type: 'scheme',
    level: 'state',
    stateCode: 'DL',
    category: 'education',
    tags: ['scholarship', 'student', 'education', 'merit'],
    preview: 'Various scholarship schemes for SC/ST, OBC, minority, and meritorious students in Delhi.',
    tagLabel: 'Scheme',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Multiple scholarship schemes for Delhi students.', 'Pre-matric and post-matric scholarships.', 'Merit-cum-means scholarships.', 'Minority community scholarships.'] },
      { title: 'Why This Matters', content: ['Financial support for education', 'Covers tuition and maintenance', 'Multiple categories eligible', 'Online application', 'Direct bank transfer', 'Encourages higher education'] },
      { title: 'Common Real-Life Problems', content: ['Application rejected', 'Amount not credited', 'Wrong category marked', 'Institution not verified', 'Deadline missed', 'Documents incomplete'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility criteria', 'Step 2: Visit scholarship portal', 'Step 3: Register and login', 'Step 4: Fill application form', 'Step 5: Upload documents', 'Step 6: Institution verification', 'Step 7: Track application', 'Step 8: Amount credited if selected', 'Step 9: Contact nodal officer for issues', 'Step 10: Renew annually'] },
      { title: 'Documents Usually Required', content: ['Aadhaar card', 'Income certificate', 'Caste certificate', 'Previous marksheets', 'Admission proof', 'Bank passbook', 'Bonafide certificate'] },
      { title: 'Where to Apply / Complain / Track', content: ['National Scholarship Portal', 'e-District Delhi', 'Social Welfare Dept', 'Minority Welfare Dept', 'Education Dept'] },
    ],
    officialLinks: [{ label: 'National Scholarship Portal', url: 'https://scholarships.gov.in' }, { label: 'e-District Delhi', url: 'https://edistrict.delhigovt.nic.in' }],
  },
  {
    id: 'dl-cm-free-coaching',
    title: 'CM Free Coaching Scheme',
    type: 'scheme',
    level: 'state',
    stateCode: 'DL',
    category: 'education',
    tags: ['coaching', 'competitive exam', 'free', 'student'],
    preview: 'Free coaching for competitive exams like UPSC, SSC, JEE, NEET for students from government schools.',
    tagLabel: 'Scheme',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Free coaching for government school students.', 'Covers UPSC, SSC, JEE, NEET, CLAT etc.', 'Tie-up with quality coaching institutes.', 'Selection through merit test.'] },
      { title: 'Why This Matters', content: ['Quality coaching free of cost', 'Equal opportunity', 'Career support', 'Selection based on merit', 'Covers major exams', 'Financial burden reduced'] },
      { title: 'Common Real-Life Problems', content: ['Not aware of scheme', 'Selection test difficult', 'Limited seats', 'Coaching center far', 'Schedule conflicts', 'Quality concerns'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Watch for application dates', 'Step 3: Apply through portal', 'Step 4: Appear for selection test', 'Step 5: If selected, join coaching', 'Step 6: Attend regularly', 'Step 7: Give mock tests', 'Step 8: Clear competitive exam', 'Step 9: Report issues to nodal officer', 'Step 10: Give feedback'] },
      { title: 'Documents Usually Required', content: ['School leaving certificate', 'Marksheets', 'Income certificate', 'Aadhaar card', 'Passport photos'] },
      { title: 'Where to Apply / Complain / Track', content: ['Education Department Delhi', 'e-District Portal', 'Empanelled coaching centers', 'Directorate of Education'] },
    ],
    officialLinks: [{ label: 'DoE Delhi', url: 'https://edudel.nic.in' }],
  },

  // Pension / Welfare
  {
    id: 'dl-old-age-pension',
    title: 'Delhi Old Age Pension Scheme',
    type: 'scheme',
    level: 'state',
    stateCode: 'DL',
    category: 'health-pension',
    tags: ['pension', 'old age', 'senior citizen', 'welfare'],
    preview: 'Monthly pension for senior citizens aged 60+ in Delhi from economically weaker sections.',
    tagLabel: 'Scheme',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Monthly pension for senior citizens.', 'Amount varies by age group.', 'Higher amount for 70+ age group.', 'Direct bank transfer.'] },
      { title: 'Why This Matters', content: ['Regular income for elderly', 'Financial security', 'No family dependency', 'Healthcare support', 'Dignity in old age', 'Easy application'] },
      { title: 'Common Real-Life Problems', content: ['Pension stopped suddenly', 'Application rejected', 'Amount not credited', 'Age verification issues', 'Bank account problems', 'Address verification failed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility (age 60+, income limit)', 'Step 2: Visit e-District portal', 'Step 3: Fill application', 'Step 4: Upload documents', 'Step 5: Verification process', 'Step 6: Pension approved', 'Step 7: Credited monthly', 'Step 8: Annual life certificate required', 'Step 9: Update bank details if changed', 'Step 10: Contact SDM for issues'] },
      { title: 'Documents Usually Required', content: ['Age proof', 'Income certificate', 'Aadhaar card', 'Bank passbook', 'Address proof', 'Passport photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['e-District Delhi', 'SDM office', 'Social Welfare Dept', 'Helpline'] },
    ],
    officialLinks: [{ label: 'e-District Delhi', url: 'https://edistrict.delhigovt.nic.in' }],
  },
  {
    id: 'dl-disability-pension',
    title: 'Delhi Disability Pension',
    type: 'scheme',
    level: 'state',
    stateCode: 'DL',
    category: 'health-pension',
    tags: ['disability', 'pension', 'PwD', 'welfare'],
    preview: 'Monthly financial assistance for persons with disabilities in Delhi.',
    tagLabel: 'Scheme',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Pension for persons with 40%+ disability.', 'Monthly assistance amount.', 'Covers various disability types.', 'UDID card holders preferred.'] },
      { title: 'Why This Matters', content: ['Regular income support', 'Healthcare expenses coverage', 'Independence for PwD', 'Social security', 'Recognition of challenges', 'Easy renewal'] },
      { title: 'Common Real-Life Problems', content: ['Disability certificate issues', 'Application rejected', 'Pension delayed', 'Amount insufficient', 'Bank account issues', 'Renewal problems'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Get disability certificate (40%+)', 'Step 2: Apply for UDID card', 'Step 3: Visit e-District portal', 'Step 4: Apply for pension', 'Step 5: Upload documents', 'Step 6: Verification', 'Step 7: Approval and credit', 'Step 8: Annual renewal', 'Step 9: Update if disability changes', 'Step 10: Contact Dept for issues'] },
      { title: 'Documents Usually Required', content: ['Disability certificate', 'UDID card', 'Aadhaar card', 'Income certificate', 'Bank passbook', 'Address proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['e-District Delhi', 'Social Welfare Dept', 'SDM office', 'Disability Helpline'] },
    ],
    officialLinks: [{ label: 'e-District Delhi', url: 'https://edistrict.delhigovt.nic.in' }],
  },

  // Additional Delhi cards
  {
    id: 'dl-ration-card',
    title: 'Delhi Ration Card Services',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'utilities',
    tags: ['ration', 'PDS', 'food', 'subsidy'],
    preview: 'Online services for ration card application, modification, and food security in Delhi.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Ration cards for subsidized food grains.', 'AAY, Priority, and Normal households.', 'Online application and correction.', 'Doorstep delivery option.'] },
      { title: 'Why This Matters', content: ['Subsidized food grains', 'Proof of residence', 'Required for schemes', 'Food security', 'Monthly entitlement', 'Doorstep delivery convenience'] },
      { title: 'Common Real-Life Problems', content: ['Card not issued', 'Name not added', 'Shop issues', 'Ration not available', 'Wrong category', 'Address change needed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit e-District portal', 'Step 2: Apply for ration card', 'Step 3: Submit documents', 'Step 4: Verification', 'Step 5: Card issued', 'Step 6: Link Aadhaar', 'Step 7: Select shop or doorstep', 'Step 8: Collect monthly quota', 'Step 9: Report issues', 'Step 10: Use grievance portal'] },
      { title: 'Documents Usually Required', content: ['Aadhaar cards', 'Address proof', 'Income proof', 'Photos', 'Old card (for modification)'] },
      { title: 'Where to Apply / Complain / Track', content: ['e-District Delhi', 'Food & Civil Supplies Dept', 'Circle Food Office', 'Helpline: 1967'] },
    ],
    officialLinks: [{ label: 'Food Delhi', url: 'https://food.delhi.gov.in' }],
  },
  {
    id: 'dl-water-sewer',
    title: 'Delhi Water & Sewer Services (DJB)',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'utilities',
    tags: ['water', 'sewer', 'DJB', 'connection'],
    preview: 'Delhi Jal Board services for water connection, billing, complaints, and free water scheme.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['DJB provides water supply and sewerage.', 'Free water up to 20,000 liters/month.', 'Online bill payment and complaints.', 'New connection applications online.'] },
      { title: 'Why This Matters', content: ['Free water scheme benefit', 'Online services', 'Complaint resolution', 'New connections', 'Billing transparency', 'Sewer connection'] },
      { title: 'Common Real-Life Problems', content: ['No water supply', 'High water bill', 'Leakage issues', 'Connection pending', 'Sewer blockage', 'Meter faulty'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit djb.gov.in', 'Step 2: Register consumer ID', 'Step 3: View/pay bills online', 'Step 4: File complaints', 'Step 5: Track status', 'Step 6: For new connection, apply online', 'Step 7: Submit documents', 'Step 8: Inspection and approval', 'Step 9: Connection given', 'Step 10: Escalate to Zonal office'] },
      { title: 'Documents Usually Required', content: ['Property proof', 'ID proof', 'NOC from owner (tenant)', 'Building plan', 'Existing connection details'] },
      { title: 'Where to Apply / Complain / Track', content: ['DJB Portal: djb.gov.in', 'DJB Customer Care', 'Zonal offices', 'CM Helpline: 181'] },
    ],
    officialLinks: [{ label: 'DJB Delhi', url: 'https://djb.gov.in' }],
  },
  {
    id: 'dl-birth-death',
    title: 'Birth & Death Registration Delhi',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'utilities',
    tags: ['birth certificate', 'death certificate', 'registration'],
    preview: 'Online registration and certificate issuance for births and deaths in Delhi.',
    tagLabel: 'Portal',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Birth/death must be registered within 21 days.', 'Online application through MCD/NDMC portals.', 'Certificates available online.', 'Delayed registration process available.'] },
      { title: 'Why This Matters', content: ['Essential identity document', 'Required for school admission', 'Passport application', 'Property matters', 'Insurance claims', 'Legal requirement'] },
      { title: 'Common Real-Life Problems', content: ['Hospital not registering', 'Name spelling wrong', 'Date incorrect', 'Home birth registration', 'Old birth registration', 'Correction needed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Hospital registers within 21 days', 'Step 2: Or visit MCD/NDMC office', 'Step 3: Fill form', 'Step 4: Submit documents', 'Step 5: Get registration number', 'Step 6: Download certificate online', 'Step 7: For corrections, apply separately', 'Step 8: Delayed registration needs affidavit', 'Step 9: Court order for very old cases', 'Step 10: Verify certificate online'] },
      { title: 'Documents Usually Required', content: ['Hospital record', 'Parents Aadhaar', 'Address proof', 'Marriage certificate', 'Affidavit (delayed)'] },
      { title: 'Where to Apply / Complain / Track', content: ['MCD Portal', 'NDMC Portal', 'CRS Portal: crsorgi.gov.in', 'Zonal offices'] },
    ],
    officialLinks: [{ label: 'MCD Delhi', url: 'https://mcdonline.nic.in' }, { label: 'CRS Portal', url: 'https://crsorgi.gov.in' }],
  },
  {
    id: 'dl-certificates',
    title: 'Caste, Income & Domicile Certificates',
    type: 'portal',
    level: 'state',
    stateCode: 'DL',
    category: 'utilities',
    tags: ['caste certificate', 'income certificate', 'domicile', 'tehsil'],
    preview: 'Online application for caste, income, and domicile certificates through e-District Delhi.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Essential certificates through e-District.', 'Time-bound delivery.', 'Digital certificates via DigiLocker.', 'Used for education, jobs, schemes.'] },
      { title: 'Why This Matters', content: ['Required for reservations', 'Scholarship eligibility', 'Government job applications', 'Scheme benefits', 'Education admission', 'Legal documentation'] },
      { title: 'Common Real-Life Problems', content: ['Application pending', 'Document verification failed', 'Certificate rejected', 'Wrong details', 'Time limit exceeded', 'Office not responding'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit e-District Delhi', 'Step 2: Register/login', 'Step 3: Select certificate type', 'Step 4: Fill form', 'Step 5: Upload documents', 'Step 6: Pay fee if applicable', 'Step 7: Track status', 'Step 8: Download when approved', 'Step 9: Get from DigiLocker', 'Step 10: Apply for correction if needed'] },
      { title: 'Documents Usually Required', content: ['Aadhaar card', 'Address proof', 'Caste proof (for SC/ST/OBC)', 'Income proof/salary slip', 'Birth certificate', 'School certificate'] },
      { title: 'Where to Apply / Complain / Track', content: ['e-District Delhi', 'SDM office', 'Tehsildar', 'Helpline: 1076'] },
    ],
    officialLinks: [{ label: 'e-District Delhi', url: 'https://edistrict.delhigovt.nic.in' }],
  },
];

// ================== UTTAR PRADESH (20 cards) ==================
export const UP_LAWS: LawScheme[] = [
  {
    id: 'up-jansunwai',
    title: 'Jansunwai - UP Grievance Portal',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'grievance',
    tags: ['grievance', 'complaint', 'government', 'CM'],
    preview: 'Chief Minister\'s grievance redressal portal for all government department complaints in UP.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Jansunwai is UP\'s flagship grievance portal.', 'Direct escalation to CM office.', 'Time-bound response mechanism.', 'Covers all government departments.'] },
      { title: 'Why This Matters', content: ['Direct access to government', 'Time-bound resolution', 'Escalation mechanism', 'Accountability', 'Track complaint status', 'No middlemen'] },
      { title: 'Common Real-Life Problems', content: ['Government office not responding', 'Service delayed', 'Corruption complaint', 'Land disputes', 'Police inaction', 'Pension issues', 'Ration problems'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit jansunwai.up.nic.in', 'Step 2: Register with mobile', 'Step 3: Select department and grievance type', 'Step 4: Describe complaint in detail', 'Step 5: Upload documents', 'Step 6: Submit and get reference number', 'Step 7: Track status online', 'Step 8: Get response from department', 'Step 9: Escalate if unsatisfied', 'Step 10: Final appeal to CM'] },
      { title: 'Documents Usually Required', content: ['ID proof', 'Address proof', 'Supporting documents', 'Previous correspondence'] },
      { title: 'Where to Apply / Complain / Track', content: ['Jansunwai Portal', 'CM Helpline: 1076', 'District Collectorate', 'Tehsil office'] },
    ],
    officialLinks: [{ label: 'Jansunwai UP', url: 'https://jansunwai.up.nic.in' }],
  },
  {
    id: 'up-rera',
    title: 'UP RERA - Real Estate Authority',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'housing-property',
    tags: ['RERA', 'real estate', 'builder', 'homebuyer', 'Noida'],
    preview: 'Uttar Pradesh RERA for project registration and homebuyer complaints in Noida, Greater Noida, Lucknow etc.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['UP RERA regulates real estate across UP.', 'Major focus on NCR region (Noida, Greater Noida).', 'Online complaint and project search.', 'Strong enforcement record.'] },
      { title: 'Why This Matters', content: ['Verify project before buying', 'File complaints online', 'Get refund for delays', 'Quality assurance', 'Builder accountability', 'Transparent process'] },
      { title: 'Common Real-Life Problems', content: ['Noida project delayed', 'Builder absconding', 'Quality issues', 'Hidden charges', 'Occupancy certificate not given', 'Registry issues'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit up-rera.in', 'Step 2: Search project registration', 'Step 3: Verify builder details', 'Step 4: File complaint online', 'Step 5: Pay fee', 'Step 6: Track status', 'Step 7: Attend hearing', 'Step 8: Get order', 'Step 9: Execute order', 'Step 10: Appeal if needed'] },
      { title: 'Documents Usually Required', content: ['Sale agreement', 'Payment receipts', 'Correspondence', 'Brochure', 'ID proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['UP RERA Portal: up-rera.in', 'UP RERA Office: Lucknow', 'Helpline on portal'] },
    ],
    officialLinks: [{ label: 'UP RERA', url: 'https://up-rera.in' }],
  },
  {
    id: 'up-efir',
    title: 'UP Police e-FIR & Citizen Portal',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'grievance',
    tags: ['police', 'FIR', 'complaint', 'crime', '112'],
    preview: 'Online FIR filing, complaint registration, and emergency services through UP Police portal.',
    tagLabel: 'Portal',
    tagColor: '#EF4444',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['UP Police offers online complaint services.', 'Dial 112 for all emergencies.', 'Track FIR status online.', 'Women safety features.'] },
      { title: 'Why This Matters', content: ['Quick complaint registration', 'Track investigation', 'Emergency response', 'Documentation', 'Transparent process', 'Women safety helpline'] },
      { title: 'Common Real-Life Problems', content: ['Theft', 'Lost documents', 'Online fraud', 'Harassment', 'Land grabbing', 'Traffic accident', 'Missing persons'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit uppolice.gov.in', 'Step 2: Select complaint type', 'Step 3: Fill details', 'Step 4: Upload evidence', 'Step 5: Get acknowledgment', 'Step 6: Track status', 'Step 7: For emergency dial 112', 'Step 8: Women can dial 1090', 'Step 9: Visit station if required', 'Step 10: Escalate to SP'] },
      { title: 'Documents Usually Required', content: ['ID proof', 'Evidence', 'Details of incident', 'Witness information'] },
      { title: 'Where to Apply / Complain / Track', content: ['UP Police Portal', 'Emergency: 112', 'Women Helpline: 1090', 'Nearest Police Station'] },
    ],
    officialLinks: [{ label: 'UP Police', url: 'https://uppolice.gov.in' }],
  },
  {
    id: 'up-slsa',
    title: 'UP State Legal Services Authority (UPSLSA)',
    type: 'scheme',
    level: 'state',
    stateCode: 'UP',
    category: 'grievance',
    tags: ['legal aid', 'free lawyer', 'Lok Adalat'],
    preview: 'Free legal aid and Lok Adalat services for eligible citizens across Uttar Pradesh.',
    tagLabel: 'Scheme',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['UPSLSA provides free legal services.', 'Lok Adalats for quick settlement.', 'Legal aid clinics.', 'Help for undertrial prisoners.'] },
      { title: 'Why This Matters', content: ['Free lawyer', 'Quick settlement', 'Legal awareness', 'Access to justice', 'Marginalized support', 'Reduced court burden'] },
      { title: 'Common Real-Life Problems', content: ['Cannot afford lawyer', 'Need quick settlement', 'Family disputes', 'Accident claims', 'Labour issues', 'Consumer matters'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit DLSA at district court', 'Step 2: Check eligibility', 'Step 3: Fill application', 'Step 4: Get lawyer assigned', 'Step 5: For Lok Adalat, apply', 'Step 6: Attend proceedings', 'Step 7: Use legal aid clinic', 'Step 8: Helpline: 15100', 'Step 9: Tele-law available', 'Step 10: Follow up'] },
      { title: 'Documents Usually Required', content: ['Application', 'Income proof', 'ID proof', 'Case documents'] },
      { title: 'Where to Apply / Complain / Track', content: ['DLSA at district courts', 'UPSLSA Office: Allahabad', 'Helpline: 15100', 'Tele-Law'] },
    ],
    officialLinks: [{ label: 'UPSLSA', url: 'https://upslsa.up.nic.in' }],
  },
  {
    id: 'up-bhulekh',
    title: 'Bhulekh UP - Land Records Portal',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'housing-property',
    tags: ['land', 'khatauni', 'property', 'records'],
    preview: 'Online land records portal for Khasra, Khatauni, and land ownership verification in UP.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Bhulekh provides online land records.', 'Khasra, Khatauni, and maps available.', 'Used for verification and transactions.', 'Mutation applications online.'] },
      { title: 'Why This Matters', content: ['Verify land ownership', 'Required for loans', 'Property transactions', 'Scheme eligibility', 'Dispute resolution', 'Mutation tracking'] },
      { title: 'Common Real-Life Problems', content: ['Name not updated', 'Wrong area', 'Mutation pending', 'Multiple claimants', 'Records not found', 'Map discrepancy'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit upbhulekh.gov.in', 'Step 2: Select district, tehsil, village', 'Step 3: Search by Khasra/name', 'Step 4: Download records', 'Step 5: For mutation, apply at Tehsil', 'Step 6: Submit sale deed', 'Step 7: Verification by Lekhpal', 'Step 8: Tehsildar approval', 'Step 9: Track online', 'Step 10: Escalate if delayed'] },
      { title: 'Documents Usually Required', content: ['Sale deed', 'Previous Khatauni', 'ID proof', 'Death certificate (inheritance)'] },
      { title: 'Where to Apply / Complain / Track', content: ['Bhulekh Portal', 'Tehsil office', 'Lekhpal', 'Jansunwai for issues'] },
    ],
    officialLinks: [{ label: 'Bhulekh UP', url: 'https://upbhulekh.gov.in' }],
  },
  {
    id: 'up-labour',
    title: 'UP Labour Department Services',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'employment',
    tags: ['labour', 'worker', 'wages', 'complaint'],
    preview: 'Labour department services for worker complaints, minimum wages, and welfare schemes in UP.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Labour Department handles worker issues.', 'Minimum wage enforcement.', 'Building workers welfare.', 'Online registration and complaints.'] },
      { title: 'Why This Matters', content: ['Wage protection', 'Worker welfare', 'Complaint resolution', 'Scheme benefits', 'Legal protection', 'Safe conditions'] },
      { title: 'Common Real-Life Problems', content: ['Wages not paid', 'Below minimum wage', 'Unsafe conditions', 'No benefits', 'Termination without notice', 'PF not deposited'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check minimum wage', 'Step 2: Document issues', 'Step 3: File complaint online', 'Step 4: Or visit Labour office', 'Step 5: Conciliation meeting', 'Step 6: Labour Court if needed', 'Step 7: Building workers register', 'Step 8: Claim benefits', 'Step 9: Join union', 'Step 10: Legal aid'] },
      { title: 'Documents Usually Required', content: ['Employment proof', 'Salary records', 'Bank statements', 'Communication', 'ID proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['UP Labour Portal', 'Labour Commissioner', 'Labour Court', 'Building Workers Board'] },
    ],
    officialLinks: [{ label: 'UP Labour', url: 'https://uplabour.gov.in' }],
  },
  {
    id: 'up-181-women',
    title: 'UP Women Helpline 181',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'women-family',
    tags: ['women', 'helpline', 'protection', '181'],
    preview: '24x7 women helpline for domestic violence, harassment, and emergency assistance in UP.',
    tagLabel: 'Portal',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['181 Women Helpline operates 24x7.', 'Immediate response for women in distress.', 'Police coordination.', 'Counseling and legal support.'] },
      { title: 'Why This Matters', content: ['Immediate help', 'Police response', 'Counseling', 'Legal aid linkage', 'Safe shelter', 'Confidential'] },
      { title: 'Common Real-Life Problems', content: ['Domestic violence', 'Harassment', 'Stalking', 'Dowry demands', 'Threats', 'Trafficking', 'Child marriage'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Call 181', 'Step 2: Describe emergency', 'Step 3: Give location', 'Step 4: Police dispatched if needed', 'Step 5: Counseling offered', 'Step 6: Safe shelter if required', 'Step 7: Legal aid connected', 'Step 8: Follow up services', 'Step 9: One Stop Centre visit', 'Step 10: File formal complaint'] },
      { title: 'Documents Usually Required', content: ['None for emergency', 'ID for follow-up services'] },
      { title: 'Where to Apply / Complain / Track', content: ['Women Helpline: 181', 'One Stop Centres', 'Women Commission UP', 'Police: 112'] },
    ],
    officialLinks: [{ label: 'WCD UP', url: 'https://mahilakalyan.up.nic.in' }],
  },
  {
    id: 'up-tehsil-certificates',
    title: 'UP Tehsil Certificate Services',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'utilities',
    tags: ['caste', 'income', 'domicile', 'certificate'],
    preview: 'Online application for caste, income, domicile, and other essential certificates in UP.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Various certificates through eDistrict UP.', 'Time-bound delivery.', 'Online tracking.', 'Integration with DigiLocker.'] },
      { title: 'Why This Matters', content: ['Essential for jobs', 'Education reservation', 'Scheme eligibility', 'Legal documentation', 'Time-bound service', 'Digital availability'] },
      { title: 'Common Real-Life Problems', content: ['Application stuck', 'Verification failed', 'Wrong information', 'Office delay', 'Rejection without reason', 'Bribe demanded'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit edistrict.up.gov.in', 'Step 2: Register', 'Step 3: Select certificate', 'Step 4: Fill form', 'Step 5: Upload documents', 'Step 6: Pay fee', 'Step 7: Track status', 'Step 8: Download certificate', 'Step 9: For issues use Jansunwai', 'Step 10: Escalate to SDM'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Address proof', 'Supporting documents', 'Photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['eDistrict UP', 'Tehsil', 'CSC Centre', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'eDistrict UP', url: 'https://edistrict.up.gov.in' }],
  },
  {
    id: 'up-kanya-sumangala',
    title: 'Mukhyamantri Kanya Sumangala Yojana',
    type: 'scheme',
    level: 'state',
    stateCode: 'UP',
    category: 'women-family',
    tags: ['girl child', 'education', 'financial aid'],
    preview: 'Financial assistance for girl children from birth to graduation in UP families with annual income up to Rs. 3 lakh.',
    tagLabel: 'Scheme',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Rs. 15,000 in stages from birth to graduation.', 'For families with income under Rs. 3 lakh.', 'Maximum 2 girls per family.', 'Direct bank transfer.'] },
      { title: 'Why This Matters', content: ['Encourages girl education', 'Financial support', 'Multiple stages covered', 'Direct transfer', 'Reduces dropout', 'Empowers girls'] },
      { title: 'Common Real-Life Problems', content: ['Application rejected', 'Amount not credited', 'Document issues', 'Income limit exceeded', 'Verification failed', 'Delay in payment'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Apply online on MKSY portal', 'Step 3: Fill details', 'Step 4: Upload documents', 'Step 5: Verification', 'Step 6: Approval', 'Step 7: Amount credited per stage', 'Step 8: Track status', 'Step 9: Update for next stage', 'Step 10: Complain on Jansunwai'] },
      { title: 'Documents Usually Required', content: ['Birth certificate', 'Aadhaar', 'Income certificate', 'Bank passbook', 'School certificate', 'Photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['MKSY Portal: mksy.up.gov.in', 'WCD Department', 'BDO/SDM office', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'Kanya Sumangala', url: 'https://mksy.up.gov.in' }],
  },
  {
    id: 'up-yuva-swarozgar',
    title: 'CM Yuva Swarozgar Yojana',
    type: 'scheme',
    level: 'state',
    stateCode: 'UP',
    category: 'employment',
    tags: ['self-employment', 'loan', 'youth', 'business'],
    preview: 'Subsidized loans for self-employment ventures for youth in Uttar Pradesh.',
    tagLabel: 'Scheme',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Loans for starting business.', 'Subsidy on loan amount.', 'For youth aged 18-40.', 'Multiple sectors covered.'] },
      { title: 'Why This Matters', content: ['Start business with support', 'Subsidy reduces burden', 'Multiple sectors eligible', 'Youth employment', 'Skill-based support', 'State backing'] },
      { title: 'Common Real-Life Problems', content: ['Loan rejected', 'Subsidy delayed', 'Complex process', 'Documentation issues', 'Bank not cooperative', 'Business viability concerns'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Prepare project report', 'Step 2: Check eligibility', 'Step 3: Apply at DIC', 'Step 4: Document verification', 'Step 5: Committee approval', 'Step 6: Bank loan sanction', 'Step 7: Start business', 'Step 8: Submit utilization proof', 'Step 9: Subsidy released', 'Step 10: Repay loan'] },
      { title: 'Documents Usually Required', content: ['Project report', 'ID proof', 'Education certificates', 'Caste certificate', 'Bank statements', 'Quotations'] },
      { title: 'Where to Apply / Complain / Track', content: ['District Industries Centre', 'MSME UP', 'Banks', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'DIC UP', url: 'https://udyogbandhu.com' }],
  },
  {
    id: 'up-awas',
    title: 'Mukhyamantri Awas Yojana UP',
    type: 'scheme',
    level: 'state',
    stateCode: 'UP',
    category: 'housing-property',
    tags: ['housing', 'affordable', 'EWS', 'construction'],
    preview: 'State housing scheme for economically weaker sections to construct or improve homes in UP.',
    tagLabel: 'Scheme',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Housing support for EWS families.', 'New construction and improvement.', 'Linked with PMAY.', 'Direct benefit transfer.'] },
      { title: 'Why This Matters', content: ['Affordable housing', 'Financial assistance', 'Home ownership', 'Improved living', 'State support', 'Land to landless'] },
      { title: 'Common Real-Life Problems', content: ['Application pending', 'Not selected', 'Amount not received', 'Quality issues', 'Verification failed', 'Land document problems'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Apply through gram panchayat', 'Step 3: Document submission', 'Step 4: Survey verification', 'Step 5: Selection', 'Step 6: Amount credited in stages', 'Step 7: Construct/improve home', 'Step 8: Photo upload', 'Step 9: Next installment', 'Step 10: Completion'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Income certificate', 'Land documents', 'Bank passbook', 'Ration card', 'Photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['Gram Panchayat', 'BDO office', 'PMAY Portal', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'PMAY UP', url: 'https://pmayg.nic.in' }],
  },
  {
    id: 'up-old-age-pension',
    title: 'UP Old Age Pension (Vridhavastha)',
    type: 'scheme',
    level: 'state',
    stateCode: 'UP',
    category: 'health-pension',
    tags: ['pension', 'old age', 'senior citizen'],
    preview: 'Monthly pension for senior citizens aged 60+ from BPL families in Uttar Pradesh.',
    tagLabel: 'Scheme',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Monthly pension for elderly.', 'For BPL families.', 'Amount varies by age.', 'Direct bank transfer.'] },
      { title: 'Why This Matters', content: ['Financial security', 'Regular income', 'Dignity in old age', 'Healthcare support', 'Independence', 'State support'] },
      { title: 'Common Real-Life Problems', content: ['Pension stopped', 'Application rejected', 'Amount delayed', 'Verification issues', 'Bank problems', 'Life certificate issues'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Apply at BDO/Nagar Palika', 'Step 3: Submit documents', 'Step 4: Verification', 'Step 5: Approval', 'Step 6: Pension starts', 'Step 7: Annual life certificate', 'Step 8: Update bank details', 'Step 9: For issues, contact SDM', 'Step 10: Use Jansunwai'] },
      { title: 'Documents Usually Required', content: ['Age proof', 'BPL certificate', 'Aadhaar', 'Bank passbook', 'Photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['BDO office', 'Nagar Palika', 'SSPY Portal', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'SSPY UP', url: 'https://sspy-up.gov.in' }],
  },
  {
    id: 'up-farmer-accident',
    title: 'UP Farmer Accident Insurance Scheme',
    type: 'scheme',
    level: 'state',
    stateCode: 'UP',
    category: 'welfare',
    tags: ['farmer', 'insurance', 'accident', 'death'],
    preview: 'Insurance coverage for farmers against accidents and death while farming in UP.',
    tagLabel: 'Scheme',
    tagColor: '#22C55E',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Insurance for registered farmers.', 'Covers death and disability.', 'Premium paid by state.', 'Quick claim settlement.'] },
      { title: 'Why This Matters', content: ['Financial protection', 'Family security', 'No premium burden', 'Quick claims', 'Covers various accidents', 'State support'] },
      { title: 'Common Real-Life Problems', content: ['Not registered', 'Claim rejected', 'Documentation issues', 'Delay in settlement', 'Process unclear', 'Amount disputes'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check farmer registration', 'Step 2: In case of accident, report immediately', 'Step 3: Get medical/death certificate', 'Step 4: Apply at Tehsil', 'Step 5: Submit documents', 'Step 6: Verification', 'Step 7: Claim approved', 'Step 8: Amount credited', 'Step 9: For issues, contact ADM', 'Step 10: Jansunwai for delays'] },
      { title: 'Documents Usually Required', content: ['Farmer registration', 'Accident report', 'Medical/death certificate', 'FIR if applicable', 'Aadhaar', 'Bank passbook'] },
      { title: 'Where to Apply / Complain / Track', content: ['Tehsil office', 'Agriculture Department', 'Insurance company', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'Agriculture UP', url: 'https://upagripardarshi.gov.in' }],
  },
  {
    id: 'up-ration-card',
    title: 'UP Ration Card & PDS Services',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'utilities',
    tags: ['ration', 'PDS', 'food', 'BPL'],
    preview: 'Online services for ration card and public distribution system in Uttar Pradesh.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Ration cards for food grains.', 'AAY, BPL, APL categories.', 'Online application.', 'Aadhaar-linked distribution.'] },
      { title: 'Why This Matters', content: ['Subsidized food', 'Identity proof', 'Scheme eligibility', 'Monthly quota', 'Food security', 'Family document'] },
      { title: 'Common Real-Life Problems', content: ['Card not issued', 'Name issues', 'Shop problems', 'Quantity shortage', 'Wrong category', 'Linking failed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Apply online', 'Step 2: Submit documents', 'Step 3: Verification', 'Step 4: Card issued', 'Step 5: Link Aadhaar', 'Step 6: Select shop', 'Step 7: Collect quota', 'Step 8: Report shortages', 'Step 9: Complain on Jansunwai', 'Step 10: Update as needed'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Address proof', 'Income proof', 'Photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['FCS UP Portal', 'Supply Inspector', 'Tehsil', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'FCS UP', url: 'https://fcs.up.gov.in' }],
  },
  {
    id: 'up-widow-pension',
    title: 'UP Widow Pension Scheme',
    type: 'scheme',
    level: 'state',
    stateCode: 'UP',
    category: 'women-family',
    tags: ['widow', 'pension', 'women', 'welfare'],
    preview: 'Monthly pension for widows from economically weaker sections in Uttar Pradesh.',
    tagLabel: 'Scheme',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Pension for widows.', 'For BPL families.', 'Direct bank transfer.', 'Annual renewal.'] },
      { title: 'Why This Matters', content: ['Financial support', 'Independence', 'Regular income', 'State protection', 'Easy process', 'Dignity'] },
      { title: 'Common Real-Life Problems', content: ['Application rejected', 'Pension stopped', 'Amount delayed', 'Death certificate issues', 'Bank problems', 'Verification failed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Apply at BDO office', 'Step 3: Submit documents', 'Step 4: Verification', 'Step 5: Approval', 'Step 6: Pension credited', 'Step 7: Life certificate annual', 'Step 8: Update bank if needed', 'Step 9: Contact SDM for issues', 'Step 10: Jansunwai for delays'] },
      { title: 'Documents Usually Required', content: ['Death certificate of husband', 'Aadhaar', 'Bank passbook', 'Income certificate', 'Age proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['BDO office', 'SSPY Portal', 'WCD Department', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'SSPY UP', url: 'https://sspy-up.gov.in' }],
  },
  {
    id: 'up-scholarship',
    title: 'UP Scholarship Portal',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'education',
    tags: ['scholarship', 'student', 'education'],
    preview: 'Comprehensive scholarship portal for pre-matric and post-matric students in UP.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Multiple scholarship schemes.', 'Pre-matric and post-matric.', 'Caste and merit based.', 'Online application.'] },
      { title: 'Why This Matters', content: ['Education support', 'Covers fees', 'Multiple categories', 'Direct transfer', 'Time-bound', 'Transparent'] },
      { title: 'Common Real-Life Problems', content: ['Application rejected', 'Amount not credited', 'Institution not verified', 'Document issues', 'Deadline missed', 'Renewal problems'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit scholarship.up.gov.in', 'Step 2: Register', 'Step 3: Select scheme', 'Step 4: Fill form', 'Step 5: Upload documents', 'Step 6: Institution verification', 'Step 7: Track status', 'Step 8: Amount credited', 'Step 9: Renew annually', 'Step 10: Contact nodal officer'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Caste certificate', 'Income certificate', 'Marksheets', 'Bank passbook', 'Admission proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['Scholarship Portal', 'Social Welfare Dept', 'Institution', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'UP Scholarship', url: 'https://scholarship.up.gov.in' }],
  },
  {
    id: 'up-birth-death',
    title: 'UP Birth & Death Registration',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'utilities',
    tags: ['birth', 'death', 'certificate', 'registration'],
    preview: 'Online registration and certificate services for births and deaths in UP.',
    tagLabel: 'Portal',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Registration within 21 days mandatory.', 'Online application.', 'Certificates downloadable.', 'Delayed registration process.'] },
      { title: 'Why This Matters', content: ['Essential document', 'School admission', 'Legal identity', 'Property matters', 'Insurance claims', 'Government services'] },
      { title: 'Common Real-Life Problems', content: ['Not registered', 'Wrong details', 'Hospital not reporting', 'Old birth registration', 'Correction needed', 'Certificate not available'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Hospital reports birth', 'Step 2: Or register at Nagar Palika/Panchayat', 'Step 3: Fill form', 'Step 4: Submit documents', 'Step 5: Get registration', 'Step 6: Download certificate', 'Step 7: For corrections, apply separately', 'Step 8: Delayed needs affidavit', 'Step 9: Court for very old cases', 'Step 10: Preserve safely'] },
      { title: 'Documents Usually Required', content: ['Hospital record', 'Parent Aadhaar', 'Address proof', 'Marriage certificate', 'Affidavit (delayed)'] },
      { title: 'Where to Apply / Complain / Track', content: ['CRS Portal', 'Nagar Palika', 'Gram Panchayat', 'Tehsil'] },
    ],
    officialLinks: [{ label: 'CRS UP', url: 'https://crsorgi.gov.in' }],
  },
  {
    id: 'up-electricity',
    title: 'UP Electricity Services (UPPCL)',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'utilities',
    tags: ['electricity', 'bill', 'connection', 'UPPCL'],
    preview: 'UPPCL online services for bill payment, new connection, and complaints in Uttar Pradesh.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['UPPCL manages electricity in UP.', 'Online bill payment.', 'New connection applications.', 'Complaint registration.'] },
      { title: 'Why This Matters', content: ['Essential utility', 'Online convenience', 'Complaint tracking', 'Multiple services', 'Subsidy schemes', 'Rural electrification'] },
      { title: 'Common Real-Life Problems', content: ['High bills', 'Supply issues', 'Connection delayed', 'Meter faulty', 'Voltage problems', 'Theft complaints'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit uppcl.org', 'Step 2: Register consumer ID', 'Step 3: Pay bills online', 'Step 4: File complaints', 'Step 5: Track status', 'Step 6: Apply new connection', 'Step 7: Submit documents', 'Step 8: Inspection', 'Step 9: Connection given', 'Step 10: Escalate to SDO'] },
      { title: 'Documents Usually Required', content: ['ID proof', 'Property proof', 'Previous bills', 'NOC if required'] },
      { title: 'Where to Apply / Complain / Track', content: ['UPPCL Portal', 'Electricity office', 'SDO office', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'UPPCL', url: 'https://www.uppcl.org' }],
  },
  {
    id: 'up-esamaj-kalyan',
    title: 'e-Samaj Kalyan UP - Social Welfare',
    type: 'portal',
    level: 'state',
    stateCode: 'UP',
    category: 'welfare',
    tags: ['social welfare', 'disability', 'pension', 'schemes'],
    preview: 'Unified portal for social welfare schemes including disability pension, scholarships, and certificates.',
    tagLabel: 'Portal',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Centralized social welfare services.', 'Pension schemes.', 'Scholarships.', 'Disability services.'] },
      { title: 'Why This Matters', content: ['Single window', 'Multiple schemes', 'Online tracking', 'Transparent', 'Time-bound', 'Easy access'] },
      { title: 'Common Real-Life Problems', content: ['Scheme not found', 'Eligibility confusion', 'Application issues', 'Document problems', 'Status unclear', 'Office visits needed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit esamajkalyan.up.gov.in', 'Step 2: Browse schemes', 'Step 3: Check eligibility', 'Step 4: Apply online', 'Step 5: Track status', 'Step 6: For issues, contact department', 'Step 7: Visit office if needed', 'Step 8: Jansunwai for grievances', 'Step 9: Follow up', 'Step 10: Provide feedback'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Category certificate', 'Income certificate', 'Bank passbook', 'Disability certificate'] },
      { title: 'Where to Apply / Complain / Track', content: ['e-Samaj Kalyan Portal', 'Social Welfare Office', 'District Magistrate', 'Jansunwai'] },
    ],
    officialLinks: [{ label: 'e-Samaj Kalyan', url: 'https://esamajkalyan.up.gov.in' }],
  },
];
