// State Laws & Schemes Data - Karnataka
// 20 cards across categories

import { LawScheme } from './lawsData';

// ================== KARNATAKA (20 cards) ==================
export const KARNATAKA_LAWS: LawScheme[] = [
  {
    id: 'ka-rera',
    title: 'Karnataka RERA',
    type: 'portal',
    level: 'state',
    stateCode: 'KA',
    category: 'housing-property',
    tags: ['RERA', 'real estate', 'builder', 'Bangalore'],
    preview: 'Karnataka Real Estate Regulatory Authority for project registration and homebuyer complaints.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['KRERA regulates real estate in Karnataka.', 'Covers Bangalore and other cities.', 'Online complaint filing.', 'Project registration mandatory.'] },
      { title: 'Why This Matters', content: ['Verify projects', 'File complaints', 'Get refunds', 'Quality assurance', 'Builder accountability', 'Transparent process'] },
      { title: 'Common Real-Life Problems', content: ['Bangalore apartment delayed', 'Builder not responding', 'Quality issues', 'Hidden charges', 'Amenities missing', 'Registry delayed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit rera.karnataka.gov.in', 'Step 2: Search project', 'Step 3: Verify registration', 'Step 4: File complaint online', 'Step 5: Pay fee', 'Step 6: Track status', 'Step 7: Attend hearing', 'Step 8: Get order', 'Step 9: Execute', 'Step 10: Appeal if needed'] },
      { title: 'Documents Usually Required', content: ['Sale agreement', 'Payment receipts', 'Correspondence', 'Brochure', 'ID proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['KRERA Portal', 'KRERA Office Bangalore', 'Helpline on portal'] },
    ],
    officialLinks: [{ label: 'Karnataka RERA', url: 'https://rera.karnataka.gov.in' }],
  },
  {
    id: 'ka-seva-sindhu',
    title: 'Seva Sindhu - Karnataka Service Portal',
    type: 'portal',
    level: 'state',
    stateCode: 'KA',
    category: 'grievance',
    tags: ['services', 'certificate', 'government', 'online'],
    preview: 'Single-window portal for all Karnataka government services, certificates, and welfare schemes.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Seva Sindhu is Karnataka\'s service delivery platform.', 'Over 700 services available.', 'Certificates, permits, and schemes.', 'Integration with Aadhaar and DigiLocker.'] },
      { title: 'Why This Matters', content: ['Single window', 'Time-bound delivery', 'Online tracking', 'No middlemen', 'Multiple services', 'Digital certificates'] },
      { title: 'Common Real-Life Problems', content: ['Certificate delayed', 'Application stuck', 'Wrong details', 'Verification failed', 'Status unclear', 'Document upload issues'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit sevasindhu.karnataka.gov.in', 'Step 2: Register with Aadhaar', 'Step 3: Select service', 'Step 4: Fill form', 'Step 5: Upload documents', 'Step 6: Pay fee if applicable', 'Step 7: Track status', 'Step 8: Download certificate', 'Step 9: For issues, use grievance', 'Step 10: Escalate if needed'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Address proof', 'Service-specific documents', 'Photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['Seva Sindhu Portal', 'Atalji Jana Snehi Kendras', 'Taluk office', 'Helpline: 080-22230282'] },
    ],
    officialLinks: [{ label: 'Seva Sindhu', url: 'https://sevasindhu.karnataka.gov.in' }],
  },
  {
    id: 'ka-efir',
    title: 'Karnataka Police e-FIR',
    type: 'portal',
    level: 'state',
    stateCode: 'KA',
    category: 'grievance',
    tags: ['police', 'FIR', 'complaint', 'crime'],
    preview: 'Online FIR filing and complaint registration with Karnataka State Police.',
    tagLabel: 'Portal',
    tagColor: '#EF4444',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Karnataka Police online services.', 'e-FIR for certain offenses.', 'Complaint tracking.', 'Emergency services via Namma 100.'] },
      { title: 'Why This Matters', content: ['Quick complaint', 'No station visit for minor issues', 'Track status', 'Documentation', 'Transparent', 'Emergency support'] },
      { title: 'Common Real-Life Problems', content: ['Mobile theft', 'Vehicle theft', 'Online fraud', 'Lost documents', 'Harassment', 'Property crimes'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit ksp.gov.in', 'Step 2: Select complaint type', 'Step 3: Fill details', 'Step 4: Upload evidence', 'Step 5: Get acknowledgment', 'Step 6: Track status', 'Step 7: Emergency dial 100', 'Step 8: Women dial 181', 'Step 9: Visit station if needed', 'Step 10: Escalate to SP'] },
      { title: 'Documents Usually Required', content: ['ID proof', 'Evidence', 'IMEI for mobile', 'RC for vehicle', 'Screenshots'] },
      { title: 'Where to Apply / Complain / Track', content: ['KSP Portal', 'Namma 100', 'Nearest Station', 'Women Helpline: 181'] },
    ],
    officialLinks: [{ label: 'Karnataka Police', url: 'https://ksp.gov.in' }],
  },
  {
    id: 'ka-kslsa',
    title: 'Karnataka State Legal Services Authority',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'grievance',
    tags: ['legal aid', 'free lawyer', 'Lok Adalat'],
    preview: 'Free legal aid and Lok Adalat services for eligible citizens in Karnataka.',
    tagLabel: 'Scheme',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['KSLSA provides free legal services.', 'Lok Adalats for quick settlement.', 'Legal aid clinics.', 'Para-legal support.'] },
      { title: 'Why This Matters', content: ['Free lawyer', 'Quick settlement', 'Legal awareness', 'Access to justice', 'Marginalized support', 'Reduced burden'] },
      { title: 'Common Real-Life Problems', content: ['Cannot afford lawyer', 'Need settlement', 'Family disputes', 'Accident claims', 'Labour issues', 'Consumer matters'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit DLSA at district court', 'Step 2: Check eligibility', 'Step 3: Fill application', 'Step 4: Get lawyer', 'Step 5: Apply Lok Adalat', 'Step 6: Attend proceedings', 'Step 7: Use legal aid clinic', 'Step 8: Helpline: 15100', 'Step 9: Tele-law available', 'Step 10: Follow up'] },
      { title: 'Documents Usually Required', content: ['Application', 'Income proof', 'ID proof', 'Case documents'] },
      { title: 'Where to Apply / Complain / Track', content: ['DLSA at courts', 'KSLSA Bangalore', 'Helpline: 15100', 'Tele-Law'] },
    ],
    officialLinks: [{ label: 'KSLSA', url: 'https://kslsa.kar.nic.in' }],
  },
  {
    id: 'ka-bhoomi',
    title: 'Bhoomi - Karnataka Land Records',
    type: 'portal',
    level: 'state',
    stateCode: 'KA',
    category: 'housing-property',
    tags: ['land', 'RTC', 'property', 'records', 'mutation'],
    preview: 'Online land records portal for RTC (Pahani), mutation, and property verification in Karnataka.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Bhoomi is Karnataka\'s land records system.', 'RTC/Pahani available online.', 'Mutation applications.', 'Maps and survey records.'] },
      { title: 'Why This Matters', content: ['Verify ownership', 'Required for loans', 'Property transactions', 'Scheme eligibility', 'Dispute resolution', 'Easy access'] },
      { title: 'Common Real-Life Problems', content: ['Name not updated', 'Area mismatch', 'Mutation pending', 'Multiple claims', 'Records not found', 'Survey issues'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit landrecords.karnataka.gov.in', 'Step 2: Select district, taluk, village', 'Step 3: Search by survey/name', 'Step 4: Download RTC', 'Step 5: For mutation, visit Taluk', 'Step 6: Submit documents', 'Step 7: Verification by officials', 'Step 8: Track online', 'Step 9: Escalate if delayed', 'Step 10: DC for appeals'] },
      { title: 'Documents Usually Required', content: ['Sale deed', 'Previous RTC', 'ID proof', 'Death certificate (inheritance)'] },
      { title: 'Where to Apply / Complain / Track', content: ['Bhoomi Portal', 'Nadakacheri (Taluk)', 'Tahsildar', 'DC office'] },
    ],
    officialLinks: [{ label: 'Bhoomi', url: 'https://landrecords.karnataka.gov.in' }],
  },
  {
    id: 'ka-labour',
    title: 'Karnataka Labour Department',
    type: 'portal',
    level: 'state',
    stateCode: 'KA',
    category: 'employment',
    tags: ['labour', 'worker', 'wages', 'complaint'],
    preview: 'Labour department services for worker complaints, minimum wages, and welfare in Karnataka.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Labour Department handles worker issues.', 'Minimum wage enforcement.', 'Building workers welfare.', 'Online complaints.'] },
      { title: 'Why This Matters', content: ['Wage protection', 'Worker welfare', 'Complaint resolution', 'Scheme benefits', 'Legal protection', 'Safe conditions'] },
      { title: 'Common Real-Life Problems', content: ['Wages not paid', 'Below minimum wage', 'Unsafe conditions', 'No PF', 'Termination issues', 'No benefits'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check minimum wage', 'Step 2: Document issues', 'Step 3: File complaint', 'Step 4: Visit Labour office', 'Step 5: Conciliation', 'Step 6: Labour Court', 'Step 7: Building workers register', 'Step 8: Claim benefits', 'Step 9: Join union', 'Step 10: Legal aid'] },
      { title: 'Documents Usually Required', content: ['Employment proof', 'Salary records', 'Bank statements', 'Communication', 'ID proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['Labour Portal', 'Labour Commissioner', 'Labour Court', 'Building Workers Board'] },
    ],
    officialLinks: [{ label: 'Labour Karnataka', url: 'https://labour.karnataka.gov.in' }],
  },
  {
    id: 'ka-women',
    title: 'Karnataka State Women Commission',
    type: 'portal',
    level: 'state',
    stateCode: 'KA',
    category: 'women-family',
    tags: ['women', 'protection', 'complaint', 'harassment'],
    preview: 'State body for women\'s protection, complaint redressal, and welfare in Karnataka.',
    tagLabel: 'Portal',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Women Commission handles women\'s issues.', 'Complaint redressal.', 'Police coordination.', 'Policy recommendations.'] },
      { title: 'Why This Matters', content: ['Quick response', 'Police action', 'Counseling', 'Legal support', 'Safe shelter', 'Awareness'] },
      { title: 'Common Real-Life Problems', content: ['Domestic violence', 'Workplace harassment', 'Dowry', 'Property denial', 'Maintenance', 'Police inaction'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Call 181', 'Step 2: Visit One Stop Centre', 'Step 3: File complaint', 'Step 4: Provide evidence', 'Step 5: Hearing', 'Step 6: Counseling', 'Step 7: Action directed', 'Step 8: Follow up', 'Step 9: Legal aid', 'Step 10: Shelter if needed'] },
      { title: 'Documents Usually Required', content: ['Complaint', 'ID proof', 'Evidence', 'FIR if filed', 'Medical reports'] },
      { title: 'Where to Apply / Complain / Track', content: ['Women Helpline: 181', 'One Stop Centres', 'Women Commission', 'Police'] },
    ],
    officialLinks: [{ label: 'Women Karnataka', url: 'https://dwcd.karnataka.gov.in' }],
  },
  {
    id: 'ka-revenue-certificates',
    title: 'Revenue Certificates (Caste, Income, Domicile)',
    type: 'portal',
    level: 'state',
    stateCode: 'KA',
    category: 'utilities',
    tags: ['caste', 'income', 'domicile', 'certificate'],
    preview: 'Online application for revenue certificates through Seva Sindhu and Nadakacheri services.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Certificates through Seva Sindhu/Nadakacheri.', 'Time-bound delivery.', 'Digital certificates.', 'DigiLocker integration.'] },
      { title: 'Why This Matters', content: ['Essential for jobs', 'Education reservation', 'Scheme eligibility', 'Legal documentation', 'Time-bound', 'Digital availability'] },
      { title: 'Common Real-Life Problems', content: ['Application pending', 'Verification failed', 'Wrong information', 'Office delay', 'Rejection', 'Corruption'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit Seva Sindhu', 'Step 2: Register', 'Step 3: Select certificate', 'Step 4: Fill form', 'Step 5: Upload documents', 'Step 6: Pay fee', 'Step 7: Track status', 'Step 8: Download certificate', 'Step 9: For issues, grievance', 'Step 10: Escalate to Tahsildar'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Address proof', 'Supporting documents', 'Photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['Seva Sindhu', 'Nadakacheri', 'Taluk office', 'DC office'] },
    ],
    officialLinks: [{ label: 'Seva Sindhu', url: 'https://sevasindhu.karnataka.gov.in' }],
  },
  {
    id: 'ka-gruha-jyothi',
    title: 'Gruha Jyothi - Free Electricity Scheme',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'utilities',
    tags: ['electricity', 'free', 'subsidy', 'utility'],
    preview: 'Free electricity up to 200 units per month for domestic consumers in Karnataka.',
    tagLabel: 'Scheme',
    tagColor: '#22C55E',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Free electricity up to 200 units.', 'For domestic consumers.', 'Registration required.', 'Direct benefit.'] },
      { title: 'Why This Matters', content: ['Significant saving', 'Family support', 'Easy registration', 'Automatic benefit', 'Monthly saving', 'State support'] },
      { title: 'Common Real-Life Problems', content: ['Not registered', 'Benefit not applied', 'Bill still coming', 'Eligibility issues', 'Registration failed', 'Multiple connections'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Visit Seva Sindhu', 'Step 2: Register for Gruha Jyothi', 'Step 3: Link electricity account', 'Step 4: Submit Aadhaar', 'Step 5: Verification', 'Step 6: Benefit applied', 'Step 7: Check bill reduction', 'Step 8: For issues, complain', 'Step 9: Contact ESCOM', 'Step 10: Update details if needed'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Electricity account number', 'Bank account (optional)'] },
      { title: 'Where to Apply / Complain / Track', content: ['Seva Sindhu', 'BESCOM/MESCOM/HESCOM', 'Taluk office', 'Helpline'] },
    ],
    officialLinks: [{ label: 'Seva Sindhu', url: 'https://sevasindhu.karnataka.gov.in' }],
  },
  {
    id: 'ka-gruha-lakshmi',
    title: 'Gruha Lakshmi - Women Cash Transfer',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'women-family',
    tags: ['women', 'cash transfer', 'welfare', 'DBT'],
    preview: 'Monthly Rs. 2,000 cash transfer to women heads of households in Karnataka.',
    tagLabel: 'Scheme',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Rs. 2,000 monthly to women heads.', 'Direct bank transfer.', 'For BPL/APL families.', 'One woman per household.'] },
      { title: 'Why This Matters', content: ['Financial independence', 'Regular income', 'Women empowerment', 'Direct transfer', 'Household support', 'State assistance'] },
      { title: 'Common Real-Life Problems', content: ['Application rejected', 'Amount not credited', 'Document issues', 'Verification failed', 'Bank problems', 'Eligibility disputes'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Apply on Seva Sindhu', 'Step 3: Submit documents', 'Step 4: Aadhaar verification', 'Step 5: Bank linking', 'Step 6: Approval', 'Step 7: Monthly credit', 'Step 8: Track status', 'Step 9: Update details', 'Step 10: Complain for issues'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Bank passbook', 'Ration card', 'Photo', 'Family declaration'] },
      { title: 'Where to Apply / Complain / Track', content: ['Seva Sindhu', 'WCD Department', 'Taluk office', 'Helpline'] },
    ],
    officialLinks: [{ label: 'Seva Sindhu', url: 'https://sevasindhu.karnataka.gov.in' }],
  },
  {
    id: 'ka-anna-bhagya',
    title: 'Anna Bhagya - Free Rice Scheme',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'welfare',
    tags: ['food', 'rice', 'PDS', 'ration'],
    preview: 'Free rice (5kg per person) for BPL and AAY ration card holders in Karnataka.',
    tagLabel: 'Scheme',
    tagColor: '#22C55E',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Free rice for BPL families.', '5 kg per person per month.', 'Through ration shops.', 'Aadhaar-linked distribution.'] },
      { title: 'Why This Matters', content: ['Food security', 'No cost', 'Monthly quota', 'Family support', 'Nutritional support', 'State assistance'] },
      { title: 'Common Real-Life Problems', content: ['Rice not available', 'Shop issues', 'Quality problems', 'Quantity shortage', 'Card not linked', 'Wrong distribution'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Have valid ration card', 'Step 2: Link Aadhaar', 'Step 3: Visit ration shop', 'Step 4: Biometric verification', 'Step 5: Collect rice', 'Step 6: Check quality', 'Step 7: Report shortages', 'Step 8: Complain for issues', 'Step 9: Use helpline', 'Step 10: Feedback for improvement'] },
      { title: 'Documents Usually Required', content: ['Ration card', 'Aadhaar for verification'] },
      { title: 'Where to Apply / Complain / Track', content: ['Fair price shop', 'Food Department', 'Taluk office', 'Helpline: 1967'] },
    ],
    officialLinks: [{ label: 'Food Karnataka', url: 'https://ahara.kar.nic.in' }],
  },
  {
    id: 'ka-shakti',
    title: 'Shakti - Free Bus Travel for Women',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'women-family',
    tags: ['bus', 'transport', 'women', 'free travel'],
    preview: 'Free travel for women in KSRTC and BMTC buses across Karnataka.',
    tagLabel: 'Scheme',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Free bus travel for women.', 'KSRTC and BMTC buses.', 'Registration required.', 'Shakti smart card issued.'] },
      { title: 'Why This Matters', content: ['Free mobility', 'Financial saving', 'Women empowerment', 'Public transport access', 'Safety', 'State support'] },
      { title: 'Common Real-Life Problems', content: ['Card not issued', 'Registration issues', 'Bus not accepting', 'Card not working', 'Long queues', 'Limited buses'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Register on Seva Sindhu', 'Step 2: Submit Aadhaar', 'Step 3: Get Shakti card', 'Step 4: Board KSRTC/BMTC bus', 'Step 5: Show card to conductor', 'Step 6: Free travel', 'Step 7: For issues, complain', 'Step 8: Contact transport dept', 'Step 9: Use helpline', 'Step 10: Feedback'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Photo', 'Mobile number'] },
      { title: 'Where to Apply / Complain / Track', content: ['Seva Sindhu', 'KSRTC/BMTC counters', 'Transport Department', 'Helpline'] },
    ],
    officialLinks: [{ label: 'Seva Sindhu', url: 'https://sevasindhu.karnataka.gov.in' }],
  },
  {
    id: 'ka-yuva-nidhi',
    title: 'Yuva Nidhi - Graduate Unemployment Allowance',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'employment',
    tags: ['youth', 'unemployment', 'allowance', 'graduate'],
    preview: 'Monthly allowance for unemployed graduates and diploma holders in Karnataka.',
    tagLabel: 'Scheme',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Rs. 3,000 for graduates, Rs. 1,500 for diploma.', 'For unemployed youth.', 'Age 18-25 years.', 'Direct bank transfer.'] },
      { title: 'Why This Matters', content: ['Financial support', 'Job search support', 'Skill development time', 'Youth welfare', 'State assistance', 'Limited period'] },
      { title: 'Common Real-Life Problems', content: ['Application rejected', 'Amount delayed', 'Eligibility issues', 'Employment status verification', 'Document problems', 'Registration failed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Register on Seva Sindhu', 'Step 3: Submit education proof', 'Step 4: Bank details', 'Step 5: Employment declaration', 'Step 6: Verification', 'Step 7: Approval', 'Step 8: Monthly credit', 'Step 9: Apply for jobs', 'Step 10: Update when employed'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Degree/Diploma certificate', 'Bank passbook', 'Domicile proof', 'Unemployment declaration'] },
      { title: 'Where to Apply / Complain / Track', content: ['Seva Sindhu', 'Employment Exchange', 'Taluk office', 'Helpline'] },
    ],
    officialLinks: [{ label: 'Seva Sindhu', url: 'https://sevasindhu.karnataka.gov.in' }],
  },
  {
    id: 'ka-arogya',
    title: 'Arogya Karnataka - Health Insurance',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'health-pension',
    tags: ['health', 'insurance', 'hospital', 'treatment'],
    preview: 'State health insurance scheme integrated with Ayushman Bharat for Karnataka residents.',
    tagLabel: 'Scheme',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Health insurance for Karnataka residents.', 'Integrated with Ayushman Bharat.', 'Cashless treatment.', 'Wide hospital network.'] },
      { title: 'Why This Matters', content: ['Free treatment', 'Cashless facility', 'Wide coverage', 'Hospital network', 'Family protection', 'State support'] },
      { title: 'Common Real-Life Problems', content: ['Card not issued', 'Hospital refusing', 'Treatment denied', 'Claim rejected', 'Out-of-pocket expenses', 'Coverage confusion'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Get health card', 'Step 3: Find empanelled hospital', 'Step 4: Show card', 'Step 5: Pre-authorization', 'Step 6: Cashless treatment', 'Step 7: For issues, complain', 'Step 8: Use helpline', 'Step 9: Grievance portal', 'Step 10: Follow up'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Ration card', 'Health card', 'Medical records'] },
      { title: 'Where to Apply / Complain / Track', content: ['Arogya Karnataka', 'Hospital Arogya Mitra', 'Seva Sindhu', 'Helpline: 104'] },
    ],
    officialLinks: [{ label: 'Arogya Karnataka', url: 'https://arogya.karnataka.gov.in' }],
  },
  {
    id: 'ka-old-age-pension',
    title: 'Karnataka Old Age Pension (Sandhya Suraksha)',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'health-pension',
    tags: ['pension', 'old age', 'senior citizen'],
    preview: 'Monthly pension for senior citizens aged 65+ from economically weaker sections in Karnataka.',
    tagLabel: 'Scheme',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Pension for elderly 65+.', 'For BPL families.', 'Monthly amount.', 'Direct bank transfer.'] },
      { title: 'Why This Matters', content: ['Financial security', 'Regular income', 'Dignity', 'Healthcare support', 'State protection', 'Easy process'] },
      { title: 'Common Real-Life Problems', content: ['Pension stopped', 'Application rejected', 'Amount delayed', 'Verification issues', 'Bank problems', 'Life certificate'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Apply on Seva Sindhu', 'Step 3: Submit documents', 'Step 4: Verification', 'Step 5: Approval', 'Step 6: Pension starts', 'Step 7: Annual life certificate', 'Step 8: Update bank', 'Step 9: Contact Taluk for issues', 'Step 10: Grievance if needed'] },
      { title: 'Documents Usually Required', content: ['Age proof', 'BPL certificate', 'Aadhaar', 'Bank passbook', 'Photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['Seva Sindhu', 'Taluk office', 'Social Welfare Dept', 'Helpline'] },
    ],
    officialLinks: [{ label: 'Seva Sindhu', url: 'https://sevasindhu.karnataka.gov.in' }],
  },
  {
    id: 'ka-disability-pension',
    title: 'Karnataka Disability Pension',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'health-pension',
    tags: ['disability', 'pension', 'PwD', 'welfare'],
    preview: 'Monthly pension for persons with disabilities in Karnataka.',
    tagLabel: 'Scheme',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Pension for persons with 40%+ disability.', 'Monthly assistance.', 'Multiple disability types.', 'UDID preferred.'] },
      { title: 'Why This Matters', content: ['Financial support', 'Independence', 'Healthcare help', 'Recognition', 'State support', 'Easy renewal'] },
      { title: 'Common Real-Life Problems', content: ['Certificate issues', 'Application rejected', 'Pension delayed', 'Amount insufficient', 'Bank issues', 'Renewal problems'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Get disability certificate', 'Step 2: Apply UDID', 'Step 3: Apply pension on Seva Sindhu', 'Step 4: Submit documents', 'Step 5: Verification', 'Step 6: Approval', 'Step 7: Monthly credit', 'Step 8: Annual renewal', 'Step 9: Update changes', 'Step 10: Grievance if issues'] },
      { title: 'Documents Usually Required', content: ['Disability certificate', 'UDID', 'Aadhaar', 'Income certificate', 'Bank passbook'] },
      { title: 'Where to Apply / Complain / Track', content: ['Seva Sindhu', 'Social Welfare Dept', 'Taluk office', 'Disability Helpline'] },
    ],
    officialLinks: [{ label: 'Seva Sindhu', url: 'https://sevasindhu.karnataka.gov.in' }],
  },
  {
    id: 'ka-ration-card',
    title: 'Karnataka Ration Card Services',
    type: 'portal',
    level: 'state',
    stateCode: 'KA',
    category: 'utilities',
    tags: ['ration', 'PDS', 'food', 'BPL'],
    preview: 'Online services for ration card application, modification, and PDS in Karnataka.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Ration cards for food grains.', 'BPL, APL, AAY categories.', 'Online application.', 'Aadhaar-linked.'] },
      { title: 'Why This Matters', content: ['Subsidized food', 'Identity proof', 'Scheme eligibility', 'Monthly quota', 'Family document', 'State support'] },
      { title: 'Common Real-Life Problems', content: ['Card not issued', 'Name issues', 'Shop problems', 'Quality issues', 'Quantity shortage', 'Linking failed'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Apply online', 'Step 2: Submit documents', 'Step 3: Verification', 'Step 4: Card issued', 'Step 5: Link Aadhaar', 'Step 6: Select shop', 'Step 7: Collect quota', 'Step 8: Report issues', 'Step 9: Complain on portal', 'Step 10: Update as needed'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Address proof', 'Income proof', 'Photo'] },
      { title: 'Where to Apply / Complain / Track', content: ['Ahara Portal', 'Food Inspector', 'Taluk office', 'Helpline: 1967'] },
    ],
    officialLinks: [{ label: 'Ahara Karnataka', url: 'https://ahara.kar.nic.in' }],
  },
  {
    id: 'ka-birth-death',
    title: 'Karnataka Birth & Death Registration',
    type: 'portal',
    level: 'state',
    stateCode: 'KA',
    category: 'utilities',
    tags: ['birth', 'death', 'certificate', 'registration'],
    preview: 'Online birth and death registration and certificate services in Karnataka.',
    tagLabel: 'Portal',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Registration within 21 days.', 'Online through Seva Sindhu.', 'Certificates downloadable.', 'Delayed registration available.'] },
      { title: 'Why This Matters', content: ['Essential document', 'School admission', 'Legal identity', 'Property matters', 'Insurance', 'Government services'] },
      { title: 'Common Real-Life Problems', content: ['Not registered', 'Wrong details', 'Hospital not reporting', 'Old registration', 'Correction needed', 'Not available online'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Hospital reports', 'Step 2: Or register at Gram Panchayat/Municipal', 'Step 3: Fill form', 'Step 4: Submit documents', 'Step 5: Registration', 'Step 6: Download certificate', 'Step 7: For corrections, apply', 'Step 8: Delayed needs affidavit', 'Step 9: Court for old cases', 'Step 10: Preserve safely'] },
      { title: 'Documents Usually Required', content: ['Hospital record', 'Parent Aadhaar', 'Address proof', 'Marriage certificate'] },
      { title: 'Where to Apply / Complain / Track', content: ['Seva Sindhu', 'CRS Portal', 'Gram Panchayat', 'Municipal office'] },
    ],
    officialLinks: [{ label: 'Seva Sindhu', url: 'https://sevasindhu.karnataka.gov.in' }],
  },
  {
    id: 'ka-scholarship',
    title: 'Karnataka Student Scholarships',
    type: 'scheme',
    level: 'state',
    stateCode: 'KA',
    category: 'education',
    tags: ['scholarship', 'student', 'education'],
    preview: 'Various scholarship schemes for SC/ST, OBC, and minority students in Karnataka.',
    tagLabel: 'Scheme',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      { title: 'Overview', content: ['Multiple scholarship schemes.', 'Pre-matric and post-matric.', 'Caste and merit based.', 'Online application.'] },
      { title: 'Why This Matters', content: ['Education support', 'Fee coverage', 'Multiple categories', 'Direct transfer', 'Time-bound', 'Transparent'] },
      { title: 'Common Real-Life Problems', content: ['Application rejected', 'Amount not credited', 'Institution issues', 'Document problems', 'Deadline missed', 'Renewal issues'] },
      { title: 'What Citizens Can Do (Steps)', content: ['Step 1: Check eligibility', 'Step 2: Visit SSP Karnataka', 'Step 3: Register', 'Step 4: Select scheme', 'Step 5: Fill form', 'Step 6: Upload documents', 'Step 7: Institution verify', 'Step 8: Track status', 'Step 9: Amount credited', 'Step 10: Contact nodal officer'] },
      { title: 'Documents Usually Required', content: ['Aadhaar', 'Caste certificate', 'Income certificate', 'Marksheets', 'Bank passbook', 'Admission proof'] },
      { title: 'Where to Apply / Complain / Track', content: ['SSP Karnataka', 'Social Welfare Dept', 'Institution', 'Helpline'] },
    ],
    officialLinks: [{ label: 'SSP Karnataka', url: 'https://ssp.karnataka.gov.in' }],
  },
];
