// State Laws & Schemes Data - Maharashtra, Delhi, UP, Karnataka
// Each state has exactly 20 cards across categories

import { LawScheme } from './lawsData';

// ================== MAHARASHTRA (20 cards) ==================
export const MAHARASHTRA_LAWS: LawScheme[] = [
  // Housing / Property
  {
    id: 'mh-maharera',
    title: 'MahaRERA - Maharashtra Real Estate Authority',
    type: 'portal',
    level: 'state',
    stateCode: 'MH',
    category: 'housing-property',
    tags: ['RERA', 'real estate', 'builder', 'homebuyer'],
    preview: 'Maharashtra RERA portal for homebuyer protection, project registration, and complaint filing.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'MahaRERA is Maharashtra\'s implementation of the Real Estate Regulation Act.',
          'All real estate projects in Maharashtra must be registered on MahaRERA portal.',
          'Provides online complaint filing, project tracking, and builder information.',
          'One of the most active RERA authorities in India with highest number of registered projects.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Verify project registration before buying property',
          'Check builder track record and past complaints',
          'File complaints online without visiting office',
          'Track project progress and approvals',
          'Get refund with interest for delayed projects',
          'Compensation for structural defects',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Builder delaying possession in Mumbai/Pune',
          'Project not registered on MahaRERA',
          'Quality issues in construction',
          'Hidden charges at possession',
          'Promised amenities not provided',
          'Carpet area less than agreement',
          'Builder not responding to queries',
          'Delayed registration of sale deed',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Visit maharera.mahaonline.gov.in',
          'Step 2: Search project by name or registration number',
          'Step 3: Check project details, approvals, and timeline',
          'Step 4: For complaints, register and login',
          'Step 5: File complaint online with documents',
          'Step 6: Pay nominal fee through online payment',
          'Step 7: Track complaint status online',
          'Step 8: Attend hearings (physical or video)',
          'Step 9: MahaRERA order is legally enforceable',
          'Step 10: Appeal to Appellate Tribunal if needed',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Agreement for sale',
          'All payment receipts',
          'Correspondence with builder',
          'Project brochure/advertisements',
          'Allotment letter',
          'ID proof',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'MahaRERA Portal: maharera.mahaonline.gov.in',
          'MahaRERA Helpline: 1800-103-7575',
          'Head Office: Mumbai',
          'Regional offices in Pune, Nagpur',
        ],
      },
    ],
    officialLinks: [
      { label: 'MahaRERA Portal', url: 'https://maharera.mahaonline.gov.in' },
      { label: 'File Complaint', url: 'https://maharera.mahaonline.gov.in' },
    ],
  },
  {
    id: 'mh-rent-control',
    title: 'Maharashtra Rent Control Act',
    type: 'law',
    level: 'state',
    stateCode: 'MH',
    category: 'housing-property',
    tags: ['rent', 'tenant', 'landlord', 'pagdi'],
    preview: 'Rent control framework for tenancies in Maharashtra covering fair rent, eviction, and dispute resolution.',
    tagLabel: 'Law',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Maharashtra Rent Control Act governs old tenancies (before 1999 in many areas).',
          'New tenancies governed by Model Tenancy Act framework.',
          'Pagdi system (old rent) still prevalent in Mumbai and Pune.',
          'Rent Court established for quick dispute resolution.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Protection from arbitrary rent increases',
          'Defined eviction grounds',
          'Fair rent determination process',
          'Tenant rights in old buildings',
          'Succession rights for family members',
          'Repairs and maintenance obligations',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Landlord forcing eviction without grounds',
          'Excessive rent increase demanded',
          'Pagdi rights dispute',
          'Building redevelopment - tenant rights',
          'Security deposit not returned',
          'Essential services cut off',
          'Repairs not done by landlord',
          'Death of tenant - succession issues',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Identify which rent law applies (old/new)',
          'Step 2: Keep all rent receipts safely',
          'Step 3: Have written agreement if possible',
          'Step 4: For disputes, approach Rent Court',
          'Step 5: Apply for fair rent determination if needed',
          'Step 6: For illegal eviction, file police complaint',
          'Step 7: Seek interim relief from court',
          'Step 8: In redevelopment, negotiate for accommodation',
          'Step 9: Consult lawyer for complex pagdi matters',
          'Step 10: Use DLSA for free legal aid',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Rent agreement/receipts',
          'Electricity/water bills in name',
          'Ration card showing address',
          'Previous correspondence',
          'Photo ID proof',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Rent Court (Small Causes Court)',
          'Civil Court',
          'District Legal Services Authority',
          'Housing Department (for MHADA)',
        ],
      },
    ],
    officialLinks: [
      { label: 'Housing Department', url: 'https://housing.maharashtra.gov.in' },
    ],
  },
  {
    id: 'mh-7-12-extract',
    title: 'Revenue Land Records (7/12 Extract)',
    type: 'portal',
    level: 'state',
    stateCode: 'MH',
    category: 'housing-property',
    tags: ['land', '7/12', 'property', 'records', 'mutation'],
    preview: 'Online access to 7/12 extract (Satbara Utara) for land records verification and property transactions.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          '7/12 Extract is the most important land record in Maharashtra.',
          'Shows ownership, area, survey number, and crop details of land.',
          'Available online through Digital Maharashtra portal.',
          'Essential for property transactions, loans, and government schemes.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Verify land ownership before purchase',
          'Required for bank loans against property',
          'Needed for PM-KISAN and farmer schemes',
          'Essential for property registration',
          'Proves ownership in disputes',
          'Shows encumbrances if any',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Name not updated after purchase',
          'Incorrect area mentioned',
          'Mutation not done after inheritance',
          'Dispute over ownership',
          'Unable to access online records',
          'Discrepancy in survey number',
          'Land records not digitized',
          'Multiple claimants on same land',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Visit mahabhulekh.maharashtra.gov.in',
          'Step 2: Select district, taluka, and village',
          'Step 3: Search by survey number or owner name',
          'Step 4: Download 7/12 extract',
          'Step 5: For mutation, apply to Talathi',
          'Step 6: Submit sale deed and required documents',
          'Step 7: Track application status online',
          'Step 8: For disputes, approach Tahsildar',
          'Step 9: Appeal to Sub-Divisional Officer',
          'Step 10: Final appeal to Revenue Court',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Sale deed (for mutation)',
          'Death certificate (for inheritance)',
          'Family tree declaration',
          'ID proof',
          'Previous 7/12 extract',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Mahabhulekh Portal: mahabhulekh.maharashtra.gov.in',
          'Talathi office',
          'Tahsildar office',
          'Sub-Divisional Office',
          'Aaple Sarkar portal for grievances',
        ],
      },
    ],
    officialLinks: [
      { label: 'Mahabhulekh', url: 'https://mahabhulekh.maharashtra.gov.in' },
      { label: 'Digital Maharashtra', url: 'https://aaplesarkar.mahaonline.gov.in' },
    ],
  },

  // Legal / Grievance
  {
    id: 'mh-aaple-sarkar',
    title: 'Aaple Sarkar - Maharashtra Grievance Portal',
    type: 'portal',
    level: 'state',
    stateCode: 'MH',
    category: 'grievance',
    tags: ['grievance', 'complaint', 'government', 'services'],
    preview: 'Single-window portal for all government service requests, certificates, and grievance redressal in Maharashtra.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Aaple Sarkar is Maharashtra\'s unified service delivery platform.',
          'Provides 400+ government services online.',
          'Grievance redressal for government department issues.',
          'Tracks application status and ensures time-bound delivery.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'No need to visit multiple offices',
          'Online application for certificates',
          'Transparent tracking of requests',
          'Escalation mechanism for delays',
          'Reduces corruption and middlemen',
          'Time-bound service delivery',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Domicile certificate application stuck',
          'Caste certificate not issued',
          'Income certificate delayed',
          'Birth/death certificate correction needed',
          'Government office not responding',
          'Application rejected without reason',
          'Multiple visits to Tehsil office',
          'Bribe demanded for services',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Visit aaplesarkar.mahaonline.gov.in',
          'Step 2: Register with mobile/Aadhaar',
          'Step 3: Select required service',
          'Step 4: Fill application form online',
          'Step 5: Upload required documents',
          'Step 6: Pay fee online if applicable',
          'Step 7: Track application status',
          'Step 8: Download certificate when ready',
          'Step 9: For delays, file grievance',
          'Step 10: Escalate to higher authority if needed',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Aadhaar card',
          'Address proof',
          'Supporting documents per service',
          'Passport photo',
          'Mobile number',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Aaple Sarkar Portal: aaplesarkar.mahaonline.gov.in',
          'Setu Kendras (for offline help)',
          'Tahsildar office',
          'District Collector office',
          'Helpline: 1800-120-8040',
        ],
      },
    ],
    officialLinks: [
      { label: 'Aaple Sarkar Portal', url: 'https://aaplesarkar.mahaonline.gov.in' },
    ],
  },
  {
    id: 'mh-efir',
    title: 'Maharashtra Police e-FIR',
    type: 'portal',
    level: 'state',
    stateCode: 'MH',
    category: 'grievance',
    tags: ['police', 'FIR', 'complaint', 'crime'],
    preview: 'Online portal for filing FIRs and complaints with Maharashtra Police for various offenses.',
    tagLabel: 'Portal',
    tagColor: '#EF4444',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Maharashtra Police offers online FIR filing for certain offenses.',
          'Citizen Portal for lodging complaints without visiting station.',
          'Mobile theft, vehicle theft, and lost documents can be reported online.',
          'Serious crimes still require physical visit to police station.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'File complaint from home',
          'No harassment at police station',
          'Documented complaint with timestamp',
          'Track investigation status online',
          'Report lost documents easily',
          'Quick reporting for insurance claims',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Mobile phone stolen',
          'Vehicle theft',
          'Lost important documents',
          'Online fraud',
          'Cheating cases',
          'Property crime',
          'Police not registering FIR',
          'Need copy of FIR',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Visit citizen.mahapolice.gov.in',
          'Step 2: Select type of complaint',
          'Step 3: Fill details with evidence',
          'Step 4: Upload supporting documents',
          'Step 5: Get acknowledgment number',
          'Step 6: Track status online',
          'Step 7: Visit station if called',
          'Step 8: For serious crimes, go to station',
          'Step 9: If FIR refused, approach SP',
          'Step 10: Use RTI for FIR copy if denied',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'ID proof',
          'IMEI number (for mobile theft)',
          'Vehicle RC (for vehicle theft)',
          'Evidence (photos, screenshots)',
          'Witness details if any',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Citizen Portal: citizen.mahapolice.gov.in',
          'Nearest Police Station',
          'Dial 100 for emergencies',
          'Cyber Crime: cybercrime.gov.in',
          'SP office for escalation',
        ],
      },
    ],
    officialLinks: [
      { label: 'Maharashtra Police Citizen Portal', url: 'https://citizen.mahapolice.gov.in' },
      { label: 'Maharashtra Police', url: 'https://mahapolice.gov.in' },
    ],
  },
  {
    id: 'mh-dlsa',
    title: 'Maharashtra Legal Services Authority (MSLSA)',
    type: 'scheme',
    level: 'state',
    stateCode: 'MH',
    category: 'grievance',
    tags: ['legal aid', 'free lawyer', 'court', 'justice'],
    preview: 'Free legal aid and Lok Adalat services for eligible citizens across Maharashtra.',
    tagLabel: 'Scheme',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'MSLSA provides free legal services to eligible persons in Maharashtra.',
          'Operates through District Legal Services Authorities in all districts.',
          'Conducts Lok Adalats for quick settlement of disputes.',
          'Provides legal awareness and para-legal volunteer support.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Free lawyer for court cases',
          'Quick settlement through Lok Adalat',
          'Legal literacy programs',
          'Help in jails and mental hospitals',
          'Women and children protection',
          'Senior citizen assistance',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Cannot afford lawyer fees',
          'Don\'t know court procedures',
          'Simple dispute needs quick resolution',
          'Motor accident compensation',
          'Cheque bounce settlement',
          'Labour dispute resolution',
          'Family matters (maintenance)',
          'Consumer disputes',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Visit nearest DLSA at district court',
          'Step 2: Check eligibility (SC/ST, women, disabled, low income)',
          'Step 3: Fill application form',
          'Step 4: Submit documents',
          'Step 5: Get panel lawyer assigned',
          'Step 6: For settlement, apply for Lok Adalat',
          'Step 7: Attend hearings/Lok Adalat',
          'Step 8: Get free legal advice at legal aid clinics',
          'Step 9: Use tele-law for remote advice',
          'Step 10: Helpline: 15100',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Application form',
          'Income certificate (below Rs. 9000/month)',
          'ID proof',
          'Caste certificate (if applicable)',
          'Case documents',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'DLSA at District Court',
          'MSLSA Helpline: 15100',
          'Tele-Law: 1800-180-7676',
          'Legal Aid Clinics',
          'Lok Adalat (at courts)',
        ],
      },
    ],
    officialLinks: [
      { label: 'MSLSA Portal', url: 'https://mslsa.gov.in' },
      { label: 'NALSA', url: 'https://nalsa.gov.in' },
    ],
  },

  // Women / Social
  {
    id: 'mh-women-commission',
    title: 'Maharashtra State Women\'s Commission',
    type: 'portal',
    level: 'state',
    stateCode: 'MH',
    category: 'women-family',
    tags: ['women', 'harassment', 'domestic violence', 'complaint'],
    preview: 'State body for women\'s protection and redressal of complaints related to violence, harassment, and discrimination.',
    tagLabel: 'Portal',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'MSCW handles complaints from women facing violence and discrimination.',
          'Can investigate and recommend action to authorities.',
          'Provides counseling and legal aid support.',
          'Works with police and courts for women\'s protection.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Quick action on complaints',
          'Counseling services',
          'Police coordination for protection',
          'Suo motu cognizance of cases',
          'Policy recommendations',
          'Legal aid support',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Domestic violence',
          'Dowry harassment',
          'Workplace harassment',
          'Property rights denial',
          'Maintenance not paid',
          'Police not taking action',
          'Sexual harassment',
          'Trafficking cases',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Call 181 Women Helpline',
          'Step 2: Visit One Stop Centre',
          'Step 3: File complaint at district office',
          'Step 4: Online complaint at MSCW portal',
          'Step 5: Provide evidence and documents',
          'Step 6: Commission will call hearing',
          'Step 7: Get counseling if needed',
          'Step 8: Commission recommends action',
          'Step 9: Follow up on implementation',
          'Step 10: Escalate to NCW if needed',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Written complaint',
          'ID proof',
          'Evidence of harassment/violence',
          'Medical reports if injured',
          'FIR copy if filed',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Women Helpline: 181',
          'One Stop Centres (Sakhi)',
          'MSCW Office: Mumbai',
          'District Women & Child Office',
          'Police (Mahila Thana)',
        ],
      },
    ],
    officialLinks: [
      { label: 'MSCW Portal', url: 'https://mscw.maharashtra.gov.in' },
      { label: 'WCD Maharashtra', url: 'https://womenchild.maharashtra.gov.in' },
    ],
  },
  {
    id: 'mh-ladki-bahin',
    title: 'Mukhyamantri Majhi Ladki Bahin Yojana',
    type: 'scheme',
    level: 'state',
    stateCode: 'MH',
    category: 'women-family',
    tags: ['women', 'financial aid', 'welfare', 'scheme'],
    preview: 'Direct financial assistance of Rs. 1,500 per month to eligible women for financial independence.',
    tagLabel: 'Scheme',
    tagColor: '#EC4899',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Ladki Bahin scheme provides Rs. 1,500 monthly to eligible women.',
          'Launched in 2024 for women\'s financial empowerment.',
          'Direct benefit transfer to bank account.',
          'Income limit and age criteria apply.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Regular income for women',
          'Financial independence',
          'No middlemen - direct transfer',
          'Helps meet daily expenses',
          'Empowers household decision-making',
          'Monthly support guaranteed',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Application not accepted',
          'Money not credited',
          'Income document issues',
          'Bank account not linked',
          'Aadhaar mismatch',
          'Already receiving other pension',
          'Eligibility confusion',
          'Status not updated',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Check eligibility criteria',
          'Step 2: Visit official portal or camp',
          'Step 3: Fill application form',
          'Step 4: Submit required documents',
          'Step 5: Aadhaar authentication',
          'Step 6: Bank account verification',
          'Step 7: Get acknowledgment receipt',
          'Step 8: Track application status',
          'Step 9: Amount credited monthly',
          'Step 10: Report issues to helpline',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Aadhaar card',
          'Bank passbook',
          'Income certificate',
          'Domicile certificate',
          'Age proof',
          'Ration card',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Official Portal (state government)',
          'Aaple Sarkar',
          'Gram Panchayat/Municipal ward',
          'Tehsil office',
          'District Women & Child Office',
        ],
      },
    ],
    officialLinks: [
      { label: 'WCD Maharashtra', url: 'https://womenchild.maharashtra.gov.in' },
      { label: 'Aaple Sarkar', url: 'https://aaplesarkar.mahaonline.gov.in' },
    ],
  },

  // Health / Welfare
  {
    id: 'mh-mahatma-phule',
    title: 'Mahatma Jyotiba Phule Jan Arogya Yojana',
    type: 'scheme',
    level: 'state',
    stateCode: 'MH',
    category: 'health-pension',
    tags: ['health', 'insurance', 'hospital', 'treatment'],
    preview: 'Free health insurance for families with yellow/orange ration card covering Rs. 1.5 to 5 lakh treatment.',
    tagLabel: 'Scheme',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'MJPJAY provides cashless treatment at empanelled hospitals.',
          'Covers families with yellow and orange ration cards.',
          'Combined with Ayushman Bharat for comprehensive coverage.',
          '996+ medical procedures covered.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Free treatment for serious illnesses',
          'Cashless at empanelled hospitals',
          'Pre and post hospitalization covered',
          'Transportation costs included',
          'Covers entire family',
          'Combined coverage up to Rs. 5 lakhs',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Hospital denying cashless treatment',
          'Procedure not in covered list',
          'Ration card not valid',
          'Hospital demanding payment',
          'Claim rejected',
          'Not aware of eligible hospitals',
          'Documents incomplete',
          'Post-treatment issues',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Check if ration card is yellow/orange',
          'Step 2: Verify eligibility on MJPJAY portal',
          'Step 3: Get health card/Ayushman card',
          'Step 4: Find empanelled hospital',
          'Step 5: Visit Arogya Mitra desk at hospital',
          'Step 6: Submit ration card and Aadhaar',
          'Step 7: Get pre-authorization for treatment',
          'Step 8: Undergo cashless treatment',
          'Step 9: For issues, call helpline',
          'Step 10: File grievance for denial',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Yellow/Orange ration card',
          'Aadhaar card',
          'Health card (if issued)',
          'Referral from PHC (some cases)',
          'Previous medical records',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'MJPJAY Portal: jeevandayee.gov.in',
          'Arogya Mitra at hospitals',
          'District Hospital',
          'Helpline: 155388',
          'Health Department',
        ],
      },
    ],
    officialLinks: [
      { label: 'MJPJAY Portal', url: 'https://www.jeevandayee.gov.in' },
      { label: 'Ayushman Maharashtra', url: 'https://arogya.maharashtra.gov.in' },
    ],
  },
  {
    id: 'mh-sanjay-gandhi-niradhar',
    title: 'Sanjay Gandhi Niradhar Anudan Yojana',
    type: 'scheme',
    level: 'state',
    stateCode: 'MH',
    category: 'health-pension',
    tags: ['pension', 'destitute', 'widow', 'disabled'],
    preview: 'Monthly pension for destitute persons including widows, disabled, orphans, and persons with serious illness.',
    tagLabel: 'Scheme',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Provides pension to persons without support or income.',
          'Categories: widows, disabled, orphans, destitute, serious illness.',
          'Monthly amount varies by category.',
          'Directly transferred to bank account.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Financial support for vulnerable',
          'Regular monthly income',
          'Covers multiple categories',
          'No middlemen in payment',
          'Helps in medical expenses',
          'Social security net',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Pension not credited',
          'Application rejected',
          'Documents incomplete',
          'Income limit exceeded marginally',
          'Verification failed',
          'Name mismatch',
          'Bank account issues',
          'Stopped without notice',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Check category eligibility',
          'Step 2: Gather required documents',
          'Step 3: Apply at Tehsil office',
          'Step 4: Or apply through Aaple Sarkar',
          'Step 5: Submit income/no-income certificate',
          'Step 6: Verification by Talathi',
          'Step 7: Approval by Tahsildar',
          'Step 8: Pension starts after approval',
          'Step 9: For issues, contact SDO',
          'Step 10: Annual renewal may be required',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Age proof',
          'Income certificate',
          'Death certificate (for widow)',
          'Disability certificate',
          'Medical reports (for illness)',
          'Ration card',
          'Aadhaar card',
          'Bank passbook',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Tehsil Office',
          'Aaple Sarkar Portal',
          'Social Welfare Department',
          'Tahsildar',
          'Sub-Divisional Officer',
        ],
      },
    ],
    officialLinks: [
      { label: 'Social Justice Dept', url: 'https://sjsa.maharashtra.gov.in' },
      { label: 'Aaple Sarkar', url: 'https://aaplesarkar.mahaonline.gov.in' },
    ],
  },

  // Food / Utilities
  {
    id: 'mh-shiv-bhojan',
    title: 'Shiv Bhojan Thali Scheme',
    type: 'scheme',
    level: 'state',
    stateCode: 'MH',
    category: 'welfare',
    tags: ['food', 'subsidized meal', 'hunger', 'thali'],
    preview: 'Subsidized nutritious meals at Rs. 5/10 per thali at designated Shiv Bhojan centers.',
    tagLabel: 'Scheme',
    tagColor: '#22C55E',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Shiv Bhojan provides affordable meals to the needy.',
          'Thali available at Rs. 5 (originally) / Rs. 10 now at centers.',
          'Nutritious meal with rice/chapati, dal, vegetables.',
          'Centers at hospitals, bus stands, and public places.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Affordable food for poor and migrants',
          'No hunger due to poverty',
          'Nutritious meal quality',
          'Multiple locations accessible',
          'No documentation needed',
          'Open to all',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Center not open',
          'Food quality poor',
          'Limited quantity',
          'Center location inconvenient',
          'Timings not suitable',
          'Overcrowding',
          'Not aware of locations',
          'Price increased',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Find nearest Shiv Bhojan center',
          'Step 2: Visit during meal timings',
          'Step 3: Pay Rs. 10 per thali',
          'Step 4: Get nutritious meal',
          'Step 5: For quality issues, complain',
          'Step 6: Report to Food & Civil Supplies',
          'Step 7: Request new center if needed',
          'Step 8: Feedback helps improve',
          'Step 9: Share location with needy',
          'Step 10: Report misuse/corruption',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'No documents required',
          'Just pay and eat',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Food & Civil Supplies Dept',
          'District Collector',
          'Municipal Corporation',
          'Aaple Sarkar for feedback',
        ],
      },
    ],
    officialLinks: [
      { label: 'Food & Civil Supplies', url: 'https://mahafood.gov.in' },
    ],
  },
  {
    id: 'mh-krushi-pump',
    title: 'Krushi Pump Vij Jodhani - Agricultural Electricity',
    type: 'scheme',
    level: 'state',
    stateCode: 'MH',
    category: 'welfare',
    tags: ['electricity', 'farmer', 'pump', 'subsidy', 'agriculture'],
    preview: 'Subsidized electricity connections and rates for agricultural pump sets in Maharashtra.',
    tagLabel: 'Scheme',
    tagColor: '#22C55E',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Agricultural electricity at subsidized rates for farmers.',
          'New pump connection scheme with government support.',
          'Flat rate or metered options available.',
          'Solar pump alternative under PM-KUSUM.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Affordable irrigation',
          'Subsidized rates for farmers',
          'New connection support',
          'Solar option saves money',
          'Essential for crop cultivation',
          'Government subsidy reduces burden',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'New connection delayed',
          'Transformer not installed',
          'Bill calculation incorrect',
          'Power supply inadequate',
          'Frequent outages during season',
          'Solar pump subsidy not sanctioned',
          'Meter not provided',
          'Wrong category charged',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Apply at MSEDCL office',
          'Step 2: Submit 7/12 extract',
          'Step 3: Pay connection charges',
          'Step 4: Get meter installed',
          'Step 5: For solar, apply on PM-KUSUM',
          'Step 6: Choose flat rate or metered',
          'Step 7: Pay bills regularly',
          'Step 8: Report power issues to MSEDCL',
          'Step 9: Complain for wrong billing',
          'Step 10: Escalate to MERC if needed',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          '7/12 extract',
          'Aadhaar card',
          'Land ownership proof',
          'Pump details',
          'Bank account details (for subsidy)',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'MSEDCL Office',
          'MSEDCL Online Portal',
          'Agriculture Department',
          'PM-KUSUM Portal',
          'MERC for escalation',
        ],
      },
    ],
    officialLinks: [
      { label: 'MSEDCL', url: 'https://www.mahadiscom.in' },
      { label: 'PM-KUSUM', url: 'https://pmkusum.mnre.gov.in' },
    ],
  },

  // Education / Jobs
  {
    id: 'mh-mahadbt',
    title: 'MahaDBT Scholarship Portal',
    type: 'portal',
    level: 'state',
    stateCode: 'MH',
    category: 'education',
    tags: ['scholarship', 'education', 'student', 'DBT'],
    preview: 'Single portal for all Maharashtra government scholarships and educational benefits through direct bank transfer.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'MahaDBT consolidates all state scholarship schemes.',
          'Over 40 scholarship schemes available.',
          'Direct benefit transfer to student accounts.',
          'Covers school, college, and professional courses.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Single application for multiple scholarships',
          'Direct transfer - no middlemen',
          'Transparent selection process',
          'Track application status online',
          'Covers various categories',
          'Reduces financial burden',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Application rejected',
          'Scholarship not credited',
          'Documents verification failed',
          'Income limit exceeded',
          'Caste certificate not accepted',
          'Bank account issues',
          'Deadline missed',
          'Already receiving another scholarship',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Visit mahadbt.maharashtra.gov.in',
          'Step 2: Register with Aadhaar',
          'Step 3: Complete profile',
          'Step 4: Check eligible scholarships',
          'Step 5: Apply for relevant schemes',
          'Step 6: Upload documents',
          'Step 7: Institution verification',
          'Step 8: Track application status',
          'Step 9: Amount credited if selected',
          'Step 10: Contact nodal officer for issues',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Aadhaar card',
          'Caste certificate',
          'Income certificate',
          'Previous marksheet',
          'Bank passbook',
          'College admission proof',
          'Bonafide certificate',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'MahaDBT Portal: mahadbt.maharashtra.gov.in',
          'College scholarship cell',
          'Social Justice Department',
          'Tribal Development Department',
          'Backward Class Department',
        ],
      },
    ],
    officialLinks: [
      { label: 'MahaDBT Portal', url: 'https://mahadbt.maharashtra.gov.in' },
    ],
  },
  {
    id: 'mh-cmegp',
    title: 'Chief Minister Employment Generation Programme',
    type: 'scheme',
    level: 'state',
    stateCode: 'MH',
    category: 'employment',
    tags: ['employment', 'self-employment', 'loan', 'subsidy', 'business'],
    preview: 'Loans with subsidy for starting small businesses and self-employment ventures in Maharashtra.',
    tagLabel: 'Scheme',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'CMEGP provides loans for self-employment ventures.',
          'Subsidy up to 25-35% on project cost.',
          'For setting up micro/small enterprises.',
          'Implemented through banks with government support.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Start business with less capital',
          'Government subsidy reduces burden',
          'Bank loan at priority rates',
          'Multiple sectors eligible',
          'Support for rural entrepreneurs',
          'Creates employment',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Bank rejecting loan',
          'Subsidy not released',
          'Project approval delayed',
          'Documentation complex',
          'Training not available',
          'Monitoring visits issues',
          'EMI burden after subsidy ends',
          'Business viability concerns',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Prepare business project report',
          'Step 2: Check eligibility criteria',
          'Step 3: Apply at District Industries Centre',
          'Step 4: Or apply through MSME portal',
          'Step 5: Document verification',
          'Step 6: Project approval committee meeting',
          'Step 7: Bank sanctions loan',
          'Step 8: Start business',
          'Step 9: Submit utilization proof',
          'Step 10: Subsidy released to bank',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Project report',
          'ID and address proof',
          'Educational qualification',
          'Caste certificate (if applicable)',
          'Property documents (for premises)',
          'Bank statements',
          'Quotations for machinery',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'District Industries Centre',
          'MSME Portal',
          'Banks (nationalized/scheduled)',
          'KVIC office',
          'Industry Department',
        ],
      },
    ],
    officialLinks: [
      { label: 'MSME Maharashtra', url: 'https://msmedi.maharashtra.gov.in' },
      { label: 'DIC Portal', url: 'https://dic.maharashtra.gov.in' },
    ],
  },

  // Housing
  {
    id: 'mh-mhada',
    title: 'MHADA Housing Lottery',
    type: 'scheme',
    level: 'state',
    stateCode: 'MH',
    category: 'housing-property',
    tags: ['housing', 'MHADA', 'lottery', 'affordable housing'],
    preview: 'Affordable housing lottery scheme by MHADA for economically weaker sections and middle income groups.',
    tagLabel: 'Scheme',
    tagColor: '#10B981',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'MHADA conducts housing lotteries for affordable homes.',
          'Categories: EWS, LIG, MIG, HIG based on income.',
          'Homes in Mumbai, Pune, Nagpur, and other cities.',
          'Computerized lottery ensures transparency.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Affordable homes in expensive cities',
          'Below market rate pricing',
          'Transparent lottery process',
          'Bank loan assistance available',
          'Government-backed quality',
          'Regular lottery announcements',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Never winning in lottery',
          'Application rejected',
          'Income limit exceeded',
          'Already own property issue',
          'Document verification failed',
          'Possession delayed',
          'Quality issues in flat',
          'Registration charges high',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Wait for MHADA lottery announcement',
          'Step 2: Check eligibility (income, no property)',
          'Step 3: Apply online during window',
          'Step 4: Pay application fee',
          'Step 5: Document verification',
          'Step 6: Lottery draw (computerized)',
          'Step 7: If selected, pay booking amount',
          'Step 8: Complete documentation',
          'Step 9: Take possession',
          'Step 10: Register property',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Income certificate/ITR',
          'Aadhaar card',
          'PAN card',
          'Address proof',
          'Affidavit (no property owned)',
          'Passport photos',
          'Bank statement',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'MHADA Portal: mhada.gov.in',
          'MHADA Regional offices',
          'Mumbai, Pune, Konkan, Nashik boards',
          'MHADA Helpline',
        ],
      },
    ],
    officialLinks: [
      { label: 'MHADA Portal', url: 'https://mhada.gov.in' },
      { label: 'Housing Dept', url: 'https://housing.maharashtra.gov.in' },
    ],
  },

  // Additional to reach 20
  {
    id: 'mh-ration-card',
    title: 'Maharashtra Ration Card Services',
    type: 'portal',
    level: 'state',
    stateCode: 'MH',
    category: 'utilities',
    tags: ['ration', 'PDS', 'food', 'BPL', 'APL'],
    preview: 'Online services for ration card application, modification, and grievance related to Public Distribution System.',
    tagLabel: 'Portal',
    tagColor: '#F59E0B',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Ration cards for subsidized food grains under PDS.',
          'Categories: AAY (Antyodaya), BPL, APL.',
          'Online application and modification.',
          'Linked to Aadhaar for authentication.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Subsidized rice, wheat, sugar, kerosene',
          'Proof of address and family',
          'Required for many government schemes',
          'Food security for poor families',
          'Monthly quota guaranteed',
          'Portability across shops',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'New card application pending',
          'Name not added/removed',
          'Shop owner misbehaving',
          'Ration not available',
          'Wrong category assigned',
          'Aadhaar linking failed',
          'Address change needed',
          'Card lost/damaged',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Apply at Aaple Sarkar portal',
          'Step 2: Fill application form',
          'Step 3: Upload documents',
          'Step 4: Visit Tehsil for verification',
          'Step 5: Track status online',
          'Step 6: For modifications, use same portal',
          'Step 7: Link Aadhaar of all members',
          'Step 8: Select fair price shop',
          'Step 9: Collect monthly quota',
          'Step 10: Complain for issues',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Aadhaar cards of all members',
          'Address proof',
          'Income proof',
          'Photos',
          'Old ration card (for modification)',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Aaple Sarkar Portal',
          'Tehsil office',
          'Food & Civil Supplies Dept',
          'AePDS Portal',
          'Helpline: 1967',
        ],
      },
    ],
    officialLinks: [
      { label: 'AePDS Portal', url: 'https://mahaepos.gov.in' },
      { label: 'Mahafood', url: 'https://mahafood.gov.in' },
    ],
  },
  {
    id: 'mh-birth-death',
    title: 'Birth & Death Certificate Services',
    type: 'portal',
    level: 'state',
    stateCode: 'MH',
    category: 'utilities',
    tags: ['birth certificate', 'death certificate', 'registration'],
    preview: 'Online registration and certificate issuance for births and deaths in Maharashtra.',
    tagLabel: 'Portal',
    tagColor: '#8B5CF6',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Birth and death must be registered within 21 days.',
          'Online registration through CRS portal.',
          'Certificates can be downloaded online.',
          'Delayed registration requires affidavit.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Essential for school admission',
          'Required for passport, Aadhaar',
          'Proof of age for all purposes',
          'Death certificate for property/pension',
          'Legal document of identity',
          'Required for insurance claims',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Hospital not registered birth',
          'Name spelling wrong',
          'Date incorrect',
          'Home delivery not registered',
          'Old birth not registered',
          'Death certificate delayed',
          'Certificate not available online',
          'Correction needed',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Hospital registers within 21 days',
          'Step 2: Or register at Municipal/Gram Panchayat',
          'Step 3: Fill form with details',
          'Step 4: Submit supporting documents',
          'Step 5: Get registration number',
          'Step 6: Download certificate from CRS',
          'Step 7: For corrections, apply separately',
          'Step 8: Delayed registration needs affidavit',
          'Step 9: Court order for very old cases',
          'Step 10: Preserve certificate safely',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Hospital discharge summary',
          'Parents Aadhaar and marriage certificate',
          'Address proof',
          'Medical certificate (for death)',
          'Affidavit (for delayed registration)',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'CRS Portal: crsorgi.gov.in',
          'Hospital (for hospital births)',
          'Municipal Corporation',
          'Gram Panchayat',
          'Tehsildar (for late registration)',
        ],
      },
    ],
    officialLinks: [
      { label: 'CRS Portal', url: 'https://crsorgi.gov.in' },
      { label: 'Aaple Sarkar', url: 'https://aaplesarkar.mahaonline.gov.in' },
    ],
  },
  {
    id: 'mh-domicile',
    title: 'Domicile & Income Certificates',
    type: 'portal',
    level: 'state',
    stateCode: 'MH',
    category: 'utilities',
    tags: ['domicile', 'income certificate', 'resident', 'tehsil'],
    preview: 'Online application for domicile certificate and income certificate through Maharashtra government portal.',
    tagLabel: 'Portal',
    tagColor: '#3B82F6',
    lastUpdated: '2024-12',
    sections: [
      {
        title: 'Overview',
        content: [
          'Domicile proves residence in Maharashtra.',
          'Income certificate shows annual family income.',
          'Required for education, jobs, and schemes.',
          'Online application through Aaple Sarkar.',
        ],
      },
      {
        title: 'Why This Matters',
        content: [
          'Required for government jobs (domicile quota)',
          'College admission preferences',
          'Scholarship eligibility',
          'Income certificate for fee waiver',
          'Scheme eligibility proof',
          'Loan applications',
        ],
      },
      {
        title: 'Common Real-Life Problems',
        content: [
          'Application stuck at Talathi',
          '15 years residence proof difficult',
          'Birth certificate from another state',
          'Income calculation disputed',
          'Certificate not issued in time',
          'Verification failed',
          'Wrong details in certificate',
          'Renewal needed',
        ],
      },
      {
        title: 'What Citizens Can Do (Steps)',
        content: [
          'Step 1: Login to Aaple Sarkar',
          'Step 2: Select service (domicile/income)',
          'Step 3: Fill application form',
          'Step 4: Upload supporting documents',
          'Step 5: Pay fee online',
          'Step 6: Application goes to Talathi/Tahsildar',
          'Step 7: Verification done',
          'Step 8: Certificate issued',
          'Step 9: Download from portal',
          'Step 10: Use for required purpose',
        ],
      },
      {
        title: 'Documents Usually Required',
        content: [
          'Birth certificate',
          'School leaving certificate',
          'Aadhaar card',
          'Ration card',
          '15 years residence proof',
          'Property documents/rent agreement',
          'Salary slip/ITR (for income)',
        ],
      },
      {
        title: 'Where to Apply / Complain / Track',
        content: [
          'Aaple Sarkar Portal',
          'Tehsil office',
          'Setu Kendra',
          'Tahsildar',
          'SDO for escalation',
        ],
      },
    ],
    officialLinks: [
      { label: 'Aaple Sarkar', url: 'https://aaplesarkar.mahaonline.gov.in' },
    ],
  },
];
